### ISSUE TITLE
Possible integer overflow during --test-it

### ISSUE THREAD

**Issue by MathRobin** [atoum/atoum#230]
I done this :

php mageekguy.atoum.phar

And get a long list of debug data.

A part of these thousands lines :

	mageekguy\atoum\tests\units\writers\std\out::test__construct() with exit code 139:
	==> output(0) ""
	=> mageekguy\atoum\tests\units\writers\std\out::testWrite() with exit code 255:
	==> output(72215) "Fatal error: Possible integer overflow in memory allocation (4 * 18446744073069528687 + 1) in phar:///home/mrobin/companeo_v6/apps/tests/php/mageekguy.atoum.phar/1/classes/score/coverage.php on line 162
	==> 
	==> Call Stack:
	==>     0.0001     638496   1. {main}() -:0
	==>     0.0994    5138032   2. mageekguy\atoum\test->runTestMethod($testMethod = 'testWrite', $tags = ???) -:1
	==>     0.1757    7139360   3. mageekguy\atoum\score\coverage->addXdebugDataForTest($test = class mageekguy\atoum\tests\units\writers\std\out { private ${mageekguy\atoum\test}:score = class mageekguy\atoum\test\score { private $case = NULL; private $dataSetKey = NULL; private $dataSetProvider = NULL; protected $passNumber = 8; protected $failAssertions = array (...); protected $exceptions = array (...); protected $runtimeExceptions = array (...); protected $errors = array (...); protected $outputs = array (...); protected $durations = array (...); protected $memoryUsages = array (...); protected $voidMethods = array (...); protected $uncompletedMethods = array (...); protected $skippedMethods = array (...); protected $coverage = class mageekguy\atoum\score\coverage { ... } }; private ${mageekguy\atoum\test}:locale = class mageekguy\atoum\locale { protected $value = NULL }; private ${mageekguy\atoum\test}:adapter = class mageekguy\atoum\adapter {  }; private ${mageekguy\atoum\test}:mockGenerator = class mageekguy\atoum\test\mock\generator { protected $test = ...; protected $adapter = class mageekguy\atoum\adapter { ... }; protected $phpMethodFactory = class Closure { ... }; protected $reflectionClassFactory = class Closure { ... }; protected $shuntedMethods = array (...); protected $overloadedMethods = array (...); protected $orphanizedMethods = array (...); protected $shuntParentClassCalls = FALSE; private ${mageekguy\atoum\mock\generator}:defaultNamespace = NULL }; private ${mageekguy\atoum\test}:reflectionMethodFactory = class Closure {  }; private ${mageekguy\atoum\test}:asserterGenerator = class mageekguy\atoum\test\asserter\generator { protected $test = ...; protected $aliases = array (...); protected $locale = class mageekguy\atoum\locale { ... }; protected $adapter = class mageekguy\atoum\adapter { ... }; protected $asserterNamespace = 'mageekguy\\atoum\\asserters\\' }; private ${mageekguy\atoum\test}:assertionManager = class mageekguy\atoum\test\assertion\manager { protected $handlers = array (...); protected $defaultHandler = class Closure { ... } }; private ${mageekguy\atoum\test}:testAdapterStorage = class mageekguy\atoum\test\adapter\storage { protected $adapters = class SplObjectStorage { ... } }; private ${mageekguy\atoum\test}:mockControllerLinker = class mageekguy\atoum\mock\controller\linker { protected $mocks = class SplObjectStorage { ... }; protected $controllers = class SplObjectStorage { ... } }; private ${mageekguy\atoum\test}:phpPath = '/usr/bin/php'; private ${mageekguy\atoum\test}:testedClassName = 'mageekguy\\atoum\\writers\\std\\out'; private ${mageekguy\atoum\test}:testedClassPath = NULL; private ${mageekguy\atoum\test}:currentMethod = 'testWrite'; private ${mageekguy\atoum\test}:testNamespace = NULL; private ${mageekguy\atoum\test}:classEngine = NULL; private ${mageekguy\atoum\test}:bootstrapFile = NULL; private ${mageekguy\atoum\test}:maxAsynchronousEngines = NULL; private ${mageekguy\atoum\test}:asynchronousEngines = 0; private ${mageekguy\atoum\test}:path = 'phar:///home/mrobin/companeo_v6/apps/tests/php/mageekguy.atoum.phar/1/tests/units/classes/writers/std/out.php'; private ${mageekguy\atoum\test}:class = 'mageekguy\\atoum\\tests\\units\\writers\\std\\out'; private ${mageekguy\atoum\test}:classNamespace = 'mageekguy\\atoum\\tests\\units\\writers\\std'; private ${mageekguy\atoum\test}:observers = array (); private ${mageekguy\atoum\test}:tags = array (); private ${mageekguy\atoum\test}:phpVersions = array (); private ${mageekguy\atoum\test}:mandatoryExtensions = array (); private ${mageekguy\atoum\test}:dataProviders = array (); private ${mageekguy\atoum\test}:testMethods = array ('testClass' => array (...), 'test__construct' => array (...), 'testWrite' => array (...)); private ${mageekguy\atoum\test}:runTestMethods = array (0 => 'testClass', 1 => 'test__construct', 2 => 'testWrite'); private ${mageekguy\atoum\test}:engines = array (); private ${mageekguy\atoum\test}:methodEngines = array (); private ${mageekguy\atoum\test}:methodsAreNotVoid = array (); private ${mageekguy\atoum\test}:executeOnFailure = array (); private ${mageekguy\atoum\test}:ignore = FALSE; private ${mageekguy\atoum\test}:debugMode = FALSE; private ${mageekguy\atoum\test}:codeCoverage = TRUE; private ${mageekguy\atoum\test}:classHasNotVoidMethods = FALSE }, $data = array ('phar:///home/mrobin/companeo_v6/apps/tests/php/mageekguy.atoum.phar/1/classes/adapter.php' => array (0 => 1, 13 => 1, 14 => -2, 18 => 1, 19 => -2), 'phar:///home/mrobin/companeo_v6/apps/tests/php/mageekguy.atoum.phar/1/classes/runner/score.php' => array (19 => -1, 20 => -1, 21 => -1, 22 => -1, 24 => -1, 25 => -2, 29 => -1, 30 => -1, 31 => -1, 32 => -2, 34 => -1, 36 => -1, 37 => -2, 41 => -1, 42 => -2, 46 => -1, 47 => -1, 48 => -1, 49 => -2, 51 => -1, 53 => -1, 54 => -2, 58 => -1, 59 => -2, 63 => -1, 64 => -1, 65 => -1, 66 => -2, 68 => -1, 70 => -1, 71 => -2, 75 => -1, 76 => -2, 80 => -1, 81 => -1, 82 => -1, 83 => -2, 85 => -1, 87 => -1, 88 => -2, 92 => -1, 93 => -2), 'phar:///home/mrobin/companeo_v6/apps/tests/php/mageekguy.atoum.phar/1/classes/test.php' => array (0 => 1, 78 => -1, 79 => -1, 80 => -1, 81 => -1, 82 => -1, 83 => -1, 84 => -1, 85 => -1, 86 => -1, 87 => -1, 88 => -1, 91 => -1, 93 => -1, 94 => -1, 95 => -1, 97 => -1, 99 => -1, 101 => -1, 102 => -1, 103 => -1, 105 => -1, 107 => -1, 109 => -1, 110 => -1, 111 => -1, 113 => -1, 115 => -1, 117 => -1, 118 => -1, 119 => -1, 121 => -1, 123 => -1, 124 => -1, 125 => -1, 126 => -1, 127 => -1, 128 => -1, 130 => -1, 131 => -1, 135 => -1, 136 => -2, 140 => 1, 141 => -2, 145 => 1, 146 => -2, 150 => -1, 152 => -1, 153 => -2, 157 => -1, 158 => -2, 162 => -1, 164 => -1, 165 => -2, 169 => -1, 170 => -2, 174 => -1, 176 => -1, 177 => -2, 181 => 1, 182 => -2, 186 => -1, 188 => -1, 189 => -2, 193 => -1, 194 => -2, 198 => -1, 200 => -1, 201 => -2, 205 => -1, 206 => -2, 210 => -1, 211 => -1, 212 => -1, 213 => -1, 216 => -1, 219 => -1, 221 => -1, 222 => -2, 226 => -1, 227 => -2, 231 => -1, 233 => -1, 234 => -2, 238 => -1, 239 => -1, 240 => -1, 241 => -1, 244 => -1, 247 => -1, 249 => -1, 250 => -2, 254 => -1, 256 => -1, 257 => -2, 261 => -1, 263 => -1, 265 => -1, 266 => -1, 267 => -1, 268 => -1, 269 => -1, 270 => -1, 271 => -1, 272 => -1, 273 => -1, 274 => -1, 277 => 1, 279 => -1, 280 => -1, 281 => -1, 282 => -1, 283 => -1, 286 => -1, 288 => -1, 289 => -1, 290 => -1, 291 => -1, 294 => -1, 295 => -1, 298 => -1, 300 => -1, 301 => -1, 302 => 1, 305 => -1, 306 => -2, 310 => -1, 312 => -1, ...), 'phar:///home/mrobin/companeo_v6/apps/tests/php/mageekguy.atoum.phar/1/classes/mock/generator.php' => array (27 => -1, 28 => -1, 29 => -1, 30 => -1, 32 => -1, 36 => -1, 37 => -2, 41 => -1, 43 => -1, 44 => -2, 48 => -1, 49 => -2, 53 => -1, 55 => -1, 56 => -2, 60 => -1, 61 => -2, 65 => -1, 67 => -1, 68 => -2, 72 => -1, 73 => -2, 77 => -1.......

I ran it on Debian squeeze with PHP 5.3, without suhosin.

**Comment by jubianchi** [comment]
Closing this one as we did not get any feedback for years.

**Comment by Hywan** [comment]
:+1:

**Comment by MathRobin** [comment]
Yep, forgot to test it. And now, I don't continue to develop in PHP. Sorry.

**Comment by jubianchi** [comment]
@MathRobin no problem ;)

the fact is we did not get feedback from any atoum user, not only you ;)
