### ISSUE TITLE
command line switches do not override .atoum.php configuration directives

### ISSUE THREAD

**Issue by gauthier** [atoum/atoum#243]
I think that switches passed on CLI should take the priority over those in configuration file.

Relates To #242 (as a side-effect example of giving priority to .atoum.php file)

**Comment by Hywan** [comment]
Is it still opened?

**Comment by jubianchi** [comment]
@Hywan yes!

**Comment by jubianchi** [comment]
* [x] `-f`/`--file` overrides `->files()` and `->directories()` from configuration file
* [x] `-d`/`--directories` overrides `->files()` and `->directories()` from configuration file
* [x] `-p`/`--php` overrides `->php()` from configuration file
* [x] `-mcn`/`--max-children-number` overrides `->maxChildrenNumber()` from configuration file
* [ ] `-ncc*`/`--no-code-coverage-*` should override configuration file
* [ ] `-tfe`/`--test-file-extensions` should override configuration file
* [ ] `-g`/`--glob` should override configuration file
* [ ] `-t`/`--tags` should override configuration file
* [ ] `-m`/`--methods` should override configuration file
* [ ] `-ns`/`--namespaces` should override configuration file
* [ ] `-af`/`--autoloader-file` should override configuration file
* [ ] `-bf`/`--bootstrap-file` should override configuration file
* [ ] `-ulr`/`--use-light-report` should override configuration file
* [ ] `-utr`/`--use-tap-report` should override configuration file
* [ ] `-xc`/`--xdebug-config` should override configuration file

**Comment by Grummfy** [comment]
@jubianchi how can we help on that one? Can you point some line of code where we can start to look at ?

**Comment by jubianchi** [comment]
@Grumfy The fix for this issue is available in #616.

I'll extract the code to fix this issue and postpone the verbose mode.

**Comment by Grummfy** [comment]
thanks
