### ISSUE TITLE
is_callable instead of instanceof \closure

### ISSUE THREAD

**Issue by guiled** [atoum/atoum#321]
I've seen in few lines a test like

    if ($value instanceof \closure)

I don't know if it could be logic, but it may fail when $value is a custom class using __invoke method.

Then I purpose to replace this test by "is_callable" which is more generic.

What do you think of this?

**Comment by jubianchi** [comment]
Since there have been no feedback since several months, I'm closing this one.

**Comment by Hywan** [comment]
Agree.
