### ISSUE TITLE
Improve code coverage

### ISSUE THREAD

**Issue by marmotz** [atoum/atoum#325]
The following issue is a translation (from french) of a very old (one year old) mail that I wrote to @mageekguy.
He never respond to me, but, maybe I'll get a discussion about that, here...

Code coverage is ONE tool but not the only one to help developpers to know the quality of their tests.
In my humble opinion, I think it's a poor helper.
And I think about one way to improve it.

Given the following class

``` php
class C1
{
    public function m1($arg1, $arg2)
    {
        // do stuff
        $this->m2();
        // do stuff
    }

    public function m2($arg1, $arg2)
    {
        // do stuff
    }
}
```

If I test only m1, code coverage is 100%. And you should think you are a good boy and all your code was tested. But you had never directly and fully tested m2.
I think we should differenciate direct code coverage (ie called just after the test method, in this case, only the m1 method code) and indirect code coverage (ie called by a method called by a test method, in this case, the m2 method code).

We should:
- hide indirect code coverage and calculate code coverage percent only with direct code coverage
- show indirect code coverage and calculate 2 code coverage:
  - direct code coverage (only with direct code coverage)
  - total code coverage (like right now)

What do you think about that ?

**Comment by Grummfy** [comment]
branch and path have been implemented ;)
