### ISSUE TITLE
Cannot mock classes with old-style constructor

### ISSUE THREAD

**Issue by Grummfy** [atoum/atoum#436]
https://gist.github.com/Grummfy/7e685187cceb1976d4c3
> atoum -d tests
> > PHP path: /usr/bin/php5
> > PHP version:
> => PHP 5.5.9-1ubuntu4.6 (cli) (built: Feb 13 2015 19:17:11)
> => Copyright (c) 1997-2014 The PHP Group
> => Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
> =>     with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
> > tests\units\A...
> [E___________________________________________________________][1/1]
> => Test duration: 0.00 second.
> => Memory usage: 0.00 Mb.
> > Total test duration: 0.00 second.
> > Total test memory usage: 0.00 Mb.
> > Running duration: 0.06 second.
> Failure (1 test, 1/1 method, 0 void method, 0 skipped method, 0 uncompleted method, 0 failure, 1 error, 0 exception)!
> > There is 1 error:
> => tests\units\A::testCoucou():
> ==> Error E_USER_ERROR in /home/jvb/workspace/tmp/atoum-php4/tests/units/A.php on line 13, generated by file /home/jvb/workspace/tmp/atoum-php4/tests/units/A.php on line 13:
Method 'mock\SuperClass::SuperClass()' does not exist

**Comment by Hywan** [comment]
@Grummfy Could you say a little more please?

**Comment by Grummfy** [comment]
look at the example : 
<code>
  function SuperClass($a = 2)
  {
     $this->a = $a;
  } 
</code>
is in error, wiutht he one you see upper

but
<code>
  function superclass($a = 2)
  {
    $this->a = $a;
  } 
</code>
is working well

**Comment by jubianchi** [comment]
> For backwards compatibility, if PHP 5 cannot find a __construct() function for a given class, and the class did not inherit one from a parent class, 
> it will search for the old-style constructor function, by the name of the class. Effectively, it means that the only case that would have compatibility 
> issues is if the class had a method named __construct() which was used for different semantics.

from http://php.net/manual/en/language.oop5.decon.php

It might be a good idea to support this...

**Comment by mikaelrandy** [comment]
It's seems the problem appears not on directly mocked classes, but on classes used by mocked classes :/

I'm currently trying to reproduce this bug on test suite, but it's quite hard for me :/
Some help is welcome

**Comment by jubianchi** [comment]
@mikaelrandy the bug seems to appear only when using non-lowercased old-style constructors : https://gist.github.com/Grummfy/7e685187cceb1976d4c3#file-superclass-php-L7-L8

**Comment by mikaelrandy** [comment]
Oh ! I miss this comment !

I will try again quickly
