### ISSUE TITLE
integration in ide

### ISSUE THREAD

**Issue by Grummfy** [atoum/atoum#447]
Hi,
In [open failed test](http://atoum.readthedocs.org/en/latest/ide.html#automatically-open-failed-tests) we see how to integrate atoum in different ide to automatically open failed test, but following the OS it change the way to do it.
With http://php.net/manual/fr/reserved.constants.php#constant.php-os we can easyly manage each os.
In the case of phpstorm or custom installation, we ask to people to add an environmental variable or to set the path like now.

I'm asking this, because in many professional team they use the same ide, so the same configuration could be welcome.

What do you think?

**Comment by Hywan** [comment]
Good idea.

**Comment by jubianchi** [comment]
@Grummfy I don't really understand what you are asking but I would be glad to talk about it with you on IRC and see what we can do to help

**Comment by jubianchi** [comment]
From the PHP documentation:

> For the name of just the operating system, consider using the PHP_OS constant, **but keep in mind this constant will contain the operating system PHP was built on**.

So `PHP_OS` might be wrong in some cases. We should then use `php_uname('s')` to do such things.

What we could do is merge similar classes into a single one which will detect the current OS and fallback to the right specific class. For example:

```php
<?php

use
    mageekguy\atoum,
    mageekguy\atoum\report\fields\runner\failures\execute
;

$stdOutWriter = new atoum\writers\std\out();
$cliReport = new atoum\reports\realtime\cli();
$cliReport->addWriter($stdOutWriter);

$cliReport->addField(new execute\phpstorm());
```

We have a new `mageekguy\atoum\report\fields\runner\failures\execute\phpstorm` which is not OS-specific. It will do the detection job and act like a `mageekguy\atoum\report\fields\runner\failures\execute\macos\phpstorm` or a `mageekguy\atoum\report\fields\runner\failures\execute\unix\phpstorm` depending on the environment.

This is the best we can do. Guessing applications' path will be harder as they can be anywhere, especially on unix. For OSX, we can easily assume they are in `/Applications` but this won't be truc for everything (`macvim`for example will be in different path depending on the installation method).

**Comment by Grummfy** [comment]
I think I will create an extension with this, I think it'sa better place than in the core of atoum.

**Comment by Grummfy** [comment]
for information => https://github.com/Grummfy/atoum-ide-helper-extension
