### ISSUE TITLE
Failed test with libxml version 2.9.2

### ISSUE THREAD

**Issue by remicollet** [atoum/atoum#449]
Failure (222 tests, 1781/1785 methods, 0 void method, 4 skipped methods, 0 uncompleted method, 0 failure, 4 errors, 0 exception)!
    > There are 4 errors:
    => mageekguy\atoum\tests\units\reports\asynchronous\xunit::testBuild():
    ==> Error E_WARNING in /builddir/build/BUILD/atoum-2.0.1/tests/units/classes/reports/asynchronous/xunit.php on line 115, generated by file /builddir/build/BUILD/atoum-2.0.1/classes/reports/asynchronous/xunit.php on line 202:
    DOMElement::setIdAttribute(): ID otherMethod already defined
    ==> Error E_WARNING in /builddir/build/BUILD/atoum-2.0.1/tests/units/classes/reports/asynchronous/xunit.php on line 115, generated by file /builddir/build/BUILD/atoum-2.0.1/classes/reports/asynchronous/xunit.php on line 202:
    DOMElement::setIdAttribute(): ID thirdMethod already defined
    ==> Error E_WARNING in /builddir/build/BUILD/atoum-2.0.1/tests/units/classes/reports/asynchronous/xunit.php on line 124, generated by file /builddir/build/BUILD/atoum-2.0.1/classes/reports/asynchronous/xunit.php on line 202:
    DOMElement::setIdAttribute(): ID thirdMethod already defined
    ==> Error E_WARNING in /builddir/build/BUILD/atoum-2.0.1/tests/units/classes/reports/asynchronous/xunit.php on line 124, generated by file /builddir/build/BUILD/atoum-2.0.1/classes/reports/asynchronous/xunit.php on line 202:
    DOMElement::setIdAttribute(): ID otherMethod already defined

Seems related to 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=766884
https://bugzilla.redhat.com/show_bug.cgi?id=1199396

**Comment by remicollet** [comment]
Upstream bug report https://bugzilla.gnome.org/show_bug.cgi?id=737840

**Comment by jubianchi** [comment]
I quickly checked those [XSDs](https://github.com/jubianchi/atoum.js/tree/master/resources/xsd) and it seems the `id` attribute is optional so, as a workaround, we can completly remove it from the XML we produce or (better) only remove it if we catch a warning.

Right now I don't really know how much work is required to bypass this bug  the only thing I know is, whicheveer solution we choose, we have to produce a valid report for common CI tools (Jenkins & co.)

**Comment by remicollet** [comment]
Just a tracker on this issue.
Upstream bug is fixed (and patch will be sson land in fedora 22+)

**Comment by jubianchi** [comment]
@remicollet thanks for the update! I'll wait for the fixed libxml to land and try to run some tests.

**Comment by Hywan** [comment]
Thanks :-)!

**Comment by mnapoli** [comment]
+1, had to install the 2.9.1 version of libxml2. With homebrew: download [this libxml2.rb version](https://raw.githubusercontent.com/Homebrew/homebrew/3e3ed2e16adf20b09dffa22bed666b10742ca0ee/Library/Formula/libxml2.rb) (pre-2.9.2), stick it in `/usr/local/Library/Formula/`, run `brew install libxml2` and then revert the `libxml2.rb` file.

It might be great to have a workaround in atoum, but right now I can't suggest one ;)

**Comment by jubianchi** [comment]
@mnapoli FYI, you can simply `brew install https://raw.githubusercontent.com/Homebrew/homebrew/3e3ed2e16adf20b09dffa22bed666b10742ca0ee/Library/Formula/libxml2.rb`, no need to mess with the Homebrew's workspace ;)

**Comment by mnapoli** [comment]
:+1: thanks good to know! And thanks for the fix!
