### ISSUE TITLE
How to skip code coverage for getter ans setter ?

### ISSUE THREAD

**Issue by macintoshplus** [atoum/atoum#450]
An annotation or configuration for skip the code coverage check for setter and getter method ?

Many entity getter and setter have no interest for unit test and code coverage !

**Comment by jubianchi** [comment]
The CLI accepts several arguments to exclude part of your code from coverage reports:

```
-nccid <directory>..., --no-code-coverage-in-directories <directory>...: Disable code coverage in directories <directory>
-nccfns <namespace>..., --no-code-coverage-for-namespaces <namespace>...: Disable code coverage for namespaces <namespace>
-nccfc <class>..., --no-code-coverage-for-classes <class>...: Disable code coverage for classes <class>
-nccfm <method>..., --no-code-coverage-for-methods <method>...: Disable code coverage for methods <method>
```

To exclude all the getters and setters just add `-nccfm '/^(?:get|set)/'` to your command line.

**Comment by macintoshplus** [comment]
Thank you for the help.

I have some function starting with 'get' that are tested. I thought to use something like a notation to indicate that the function is to be ignored for coverage code.

I'll have to test this way!

**Comment by kao98** [comment]
Personnaly I pay attention to cover getter and setter inside other more relevant tests. So I'm sure my coverage is real and fine.

But this is actually one personnal test design strategy.

**Comment by Hywan** [comment]
I am going to close this issue. If you think we didn't answer to your question, ping back and I will re-open it!
