### ISSUE TITLE
Simple output with no ansi codes

### ISSUE THREAD

**Issue by evert** [atoum/atoum#461]
I would love a new command line option in atoum that ensures that no special ANSI codes are used.

Currently a bunch of ansi codes are used, which messes up travis output:

Example here: https://travis-ci.org/fruux/sabre-katana/jobs/59609852

**Comment by jubianchi** [comment]
Hi @evert !

You are right, during the build, the output is kind of messy on travis. When the build finishes, travis reformats the output so it becomes clean.
You can already enable the TAP report on travis if you want to get a clean (but more verbose output) using the `-utr` command line flag. It does not use any ANSI sequence.

**Comment by evert** [comment]
I actually did not realize that the output cleans up after the build. I guess I was just inpatient. In that case, this is not really an issue for me. Feel free to close it again.
