### ISSUE TITLE
Disabling child processes

### ISSUE THREAD

**Issue by evert** [atoum/atoum#462]
I'm trying to debug problems in our unittests, and I usually do so by using step-through debugging in xdebug (in vim).

Unfortunately with atoum it appears as if tests are run in child processes, so while I can step through the parent process, I have no way to do that with the child process.

Is there a way to disable this feature so I can debug my unittests?

**Comment by mageekguy** [comment]
You can use the `-xc` option on the command line, see https://github.com/atoum/atoum/issues/244#issuecomment-22619460 for more information.

**Comment by evert** [comment]
Great, will try this!

**Comment by jubianchi** [comment]
@evert can we close this issue or do you still have issues with this?

**Comment by evert** [comment]
All is good, thank you!
