### ISSUE TITLE
Asserter 'string' does not exist

### ISSUE THREAD

**Issue by nicocans** [atoum/atoum#464]
Hello,
I am using Atoum with Behat, it works, but I have a strange issue using asserter string, for example here:
                $this->assert          
                    ->string($text1)
                        ->contains($product)
                ; 
If I use instead variable(), it passes, but variable has not the contains() asserter.

**Comment by Hywan** [comment]
The `string` asserter has a `contains` assertion (https://github.com/atoum/atoum/blob/9f17fa0a729294f4fcbb1a085f99ae612dc36cb5/classes/asserters/phpString.php#L157-L169).  What is your error exactly?

**Comment by nicocans** [comment]
Sorry if i am not clear. If I use
$this->assert
->string($text1)
->isEqualTo($product)
; 
throws the following error: "Asserter 'string' does not exist". But this works:
$this->assert
->variable($text1)
->isEqualTo($product)
; 
But I can't use the trick with contains(), because variable($text1)->contains($product) does not exist.

**Comment by jubianchi** [comment]
@nicocans Is there any place we can see your sorce code ?

Perhaps it's just a configuration/integration problem. Using atoum asserters in Behat might require some tricks ;)

The only thing I see with the `string` asserter is that it is an alias on the `phpString` asserter (required to support php7). Could you try things like `->integer(42)->isLessThan(1337)` or `->array([1, 2, 3])->contains(3)`. The `integer` and `array` asserters are also aliases. If you get the same error with tthose two asserters then we can easily find the source of the bug.

thanks!

**Comment by nicocans** [comment]
float is OK, but same error with array:
Asserter 'array' does not exist (mageekguy\atoum\exceptions\logic\invalidArgument)

I'm not sure i could manage this trick. Changing string() to phpString() it works for me, so I can close the issue. thx.

**Comment by jubianchi** [comment]
@nicocans feel free to ping me on freenode##atoum if you want to fully enable aliases. I should have a base context working with behat somewhere ;)

**Comment by Hywan** [comment]
@nicocans What is your PHP version please?

**Comment by nicocans** [comment]
5.5
