### ISSUE TITLE
Comment? why no comment?

### ISSUE THREAD

**Issue by Grummfy** [atoum/atoum#465]
Hi,
I was very surprise to fin almost no comment in the code of atoum. Is there any reason?

**Comment by kao98** [comment]
Hi, 
I must say I was surprised too!
Could it be possible to start something to improve code documentation? I though it was really hard to begin contributing to atoum mainly because of that actually.

**Comment by GuillaumeDievart** [comment]
Hi,

I think all you search are in the tests: https://github.com/atoum/atoum/tree/master/tests/units

My thought, the comments code must be used, when the code is not hard to understand (KISS missing ?), or when a hack is used. All the rest of time, comments are useless.

This thought is mine.

**Comment by kao98** [comment]
[Code tells you How, Comments tells you why](http://blog.codinghorror.com/code-tells-you-how-comments-tell-you-why/).

Atoum's code is IMO not documented enough. Well, not the user doc which is pretty good, but documentation for contributors. It is hard to come in, Grummfy just point something I already though, and I guess we're not alone.

Code is always obvious for its author. Actually it is often not for readers.

Try to find out some code of the best developers in the world, you'll see it is enormously documented. To name one: John Carmack.

**Comment by Grummfy** [comment]
For me it's an issue. It limit external contribution and need more time to get in the code and start changing things

**Comment by Hywan** [comment]
I am going to close this issue. If you think it is not answered, feel free to ask and I will re-open it!

**Comment by Grummfy** [comment]
for me the issue is not resolved ... there is still no comment ...

**Comment by Hywan** [comment]
@Grummfy The question is: Do we want to add comments?

**Comment by mikaelrandy** [comment]
I agree with @Grummfy : the lack of doc is a real obstacle to enter to the code.
atoum's code have a lot of magic, of central classes hard to understand and the doc could be very helpful for new contributors (like i am)

**Comment by Hywan** [comment]
See #522 for the issue then. This one is a question.
