### ISSUE TITLE
PHP 7 compat: "Cannot use 'string' as class name as it is reserved"

### ISSUE THREAD

**Issue by pascalchevrel** [atoum/atoum#469]
Launching Atoum tests in PHP 7 hits this error:
==> Error FATAL ERROR in /var/www/transvision/tests/units/Transvision/VersionControl.php on unknown line, generated by file /var/www/transvision/vendor/atoum/atoum/classes/asserters/string.php on line 12:
Cannot use 'string' as class name as it is reserved

The list of reserved keywords introduced by PHP 7 is here:
https://github.com/php/php-src/blob/php-7.0.0alpha2/UPGRADING#L379

**Comment by GuillaumeDievart** [comment]
Hello @pascalchevrel ,

update your atoum version: https://github.com/atoum/atoum/blob/master/classes/asserters/phpString.php#L12

This class is renamed since 3 months.

**Comment by pascalchevrel** [comment]
Thanks for the information, I see it is in the 2.x branch and my project was still on 1.x

**Comment by Hywan** [comment]
@pascalchevrel You are probably not likely to get a regression. We bumped the `x` in `x.y.z` because of a very small regression that mainly impact extensions. I guess you can upgrade safely.
