### ISSUE TITLE
A php cs fixer config file?

### ISSUE THREAD

**Issue by Grummfy** [atoum/atoum#473]
Hello,
when I read http://docs.atoum.org/fr/latest/participer.html#convention-de-codage
I'm wondering if we should not have a phpcs fixer config file here?

**Comment by jubianchi** [comment]
Would be great but we'll also have to provide some specific fixers to handle our specific coding standards.

**Comment by Hywan** [comment]
You could take a look at https://github.com/hoaproject/Devtools/tree/master/Resource/PHPCSFixer if needed.

**Comment by Hywan** [comment]
But :+1: for me :-).

**Comment by GuillaumeDievart** [comment]
There does not exist a tool able of creating coding rules based on the code of the project?

**Comment by Hywan** [comment]
@GuillaumeDievart Ouch, hardcore…

**Comment by Grummfy** [comment]
probably possible to deduct from some class but it will be hard to do.

**Comment by jubianchi** [comment]
closed by 9fbe09dee64c6d0077866
