### ISSUE TITLE
callback function or file inclusion at test suite end

### ISSUE THREAD

**Issue by lce-fr** [atoum/atoum#481]
I try to use docker to test classes relying on a postgresql database. Sadly, if I do not put a sleep(5) in the setup function after 

```php
system('docker run -p 5432:5432 -d --name test-postgres -e POSTGRES_PASSWORD=test -v /var/docker/postgres postgres')
```
the postgre server is not ready when test are launch.

I would like to avoid this 5 second downtime so I put the docker file starting in the .atoum.php which is only run once. 

In that case I would need a file run only at the end of the test suite in order to stop the container and remove it.

Kind regards

**Comment by Hywan** [comment]
@lce-fr What about http://php.net/register_shutdown_function?

**Comment by lce-fr** [comment]
It does not work by registering one in the .atoum.php file. In the atoum scripts/runner.php file there is a register_shutdown_function  already registered which exits the script therefore preventing other shutdown functions defined after to be executed.

**Comment by Hywan** [comment]
Hmm, asking @mageekguy or @jubianchi?

**Comment by jubianchi** [comment]
@lce-fr Hi!

atoum is not meant to manage the test environment this is why your are having trouble booting your docker container from atoum.

I would suggest making this part of a more global test script, written in pure shell or in your build script (in Jenkins for example):

```sh
docker run ...

sleep 5

bin/atoum -d tests/unit

docker rm ...
```

If you still want to do it in PHP, through atoum, you will have no choice and the `.atoum.php` is probably the only file you can put your commands in.

Another problem you might have with putting the docker command in the `.atoum.php` is that your database will be shared among all your tests. If you want a true isolation, I'll suggest you to move this command (`docker run ...`) in the `setUp` method of your tests and add the shutdown command (`docker rm ...`) in the `tearDown` method.

**Comment by lce-fr** [comment]
Hi @jubianchi,

I have indeed switched to your approach with a test.sh script wich launch docker containers and remove them afterward.

Right now I have put a create table statement in the setup method and a drop table in the teardown method. Maybe I could improve that by creating one table by test method so that each test is isolated.

If you want to look at the setup and share comments you are very welcome : http://github.com/lce-fr/php-postgresql-repository

I don't know if there would be other cases for a test suite end script inclusion so I let you close the issue if you feel it is required. It is ok for me ! 

Kind regards

**Comment by jubianchi** [comment]
> Maybe I could improve that by creating one table by test method so that each test is isolated.

@lce-fr Indeed you can easily improve this by using the `beforeTestMethod` and `afterTestMethod` of atoum tests. Those will be executed before and after each test method, giving you an isolation a the method level.

You can move your `CREATE TABLE` and `DROP TABLE` statements to those hook methods. The only thing you'll have to take care of is to use unique names for your table: for example, the test method name which is passed as an argument of `beforeTestMethod` and `afterTestMethod`. Using unique names will be mandatory as test methods (and their hooks) are run concurrently.

Hope it helps ;)
