### ISSUE TITLE
Adopt the Open CoC

### ISSUE THREAD

**Issue by jubianchi** [atoum/atoum#483]
http://todogroup.org/opencodeofconduct/#atoum/team@atoum.org

What do you think about adopting this CoC ?
CoCs are kind of a trend these days but I think it can be particularly good for us, @atoum/all.
we had too much heated discussions here, sometimes for good and sometimes for bad (or even for nothing). 

By adopting such a CoC I hope everyone will keep in mind that we all have problems, experiences, opinions we can express and we should discuss them in a kindly manner.

**Comment by Hywan** [comment]
:+1: even if I feel CoC is useless… but we can refer to it when people are in a disagreement.

**Comment by mikaelrandy** [comment]
In my mind, CoC is useless ... until it become usefull ;)
We don't need to refer to the CoC every time, but in case of problems, we can refer to it

**Comment by Hywan** [comment]
Where to put this?
