### ISSUE TITLE
version of atoum in top of the command line

### ISSUE THREAD

**Issue by Grummfy** [atoum/atoum#500]
Hello,
today when we launch the atoum command to test something we have something like this :
> PHP path: /usr/bin/php5
> PHP version:
=> PHP 5.6.4-4ubuntu6.2 (cli) (built: Jul  2 2015 15:29:28)
=> Copyright (c) 1997-2014 The PHP Group
=> Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
=>     with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
=>     with Xdebug v2.2.6, Copyright (c) 2002-2014, by Derick Rethans
> ...

What I want is something like this :
> PHP path: /usr/bin/php5
> PHP version:
=> PHP 5.6.4-4ubuntu6.2 (cli) (built: Jul  2 2015 15:29:28)
=> Copyright (c) 1997-2014 The PHP Group
=> Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
=>     with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
=>     with Xdebug v2.2.6, Copyright (c) 2002-2014, by Derick Rethans
> atoum version DEVELOPMENT-1.2.0 by Frédéric Hardy 
> atoum path: phar:///usr/share/atoum/mageekguy.atoum.phar
> ...

for example

**Comment by jubianchi** [comment]
:+1:

**Comment by Hywan** [comment]
:+1:
