### ISSUE TITLE
Add a callStaticOnTestedInstance() function

### ISSUE THREAD

**Issue by mikaelrandy** [atoum/atoum#514]
Atoum proposes [some very helpfully function around testedInstance](http://docs.atoum.org/en/latest/written_help.html#newtestedinstance-testedinstance).

But, to execute static method on tested class, or call constant on it is difficult:
```php
$this
    ->given($testedClass = $this->testedClass->getClass())
        ->then
            ->variable($testedClass::myStaticMethod())
```

or
```php
$this
    ->then
        ->variable(call_user_func([ $this->getTestedClassName(), 'myStaticMethod’]))
```

It should be very helpful to have a `callStaticOnTestedClass('myStaticMethod')` or `getConstantOnTestedClass('constName')`

**Comment by mikaelrandy** [comment]
@jubianchi can you explain to me how `newTestedInstance` and other related methods works ?

The only code i found to define theses methods is in `classes/test.php`, but i dont understand where `$instance` is really instantiated.

Do you have any clue to help me to stard ?

**Comment by jubianchi** [comment]
let's check this tomorrow omIRC, ok ?

**Comment by jubianchi** [comment]
@mikaelrandy as said on IRC, the magic is here:

* https://github.com/atoum/atoum/blob/master/classes/factory/builder.php#L11

The factory works on a reference held by the `$instance` variable. But I think you won't have to use this as you are working on static calls here.

**Comment by mikaelrandy** [comment]
@jubianchi @Hywan this PR is ready for review
