### ISSUE TITLE
atoum --version always gives dev-master

### ISSUE THREAD

**Issue by pascalchevrel** [atoum/atoum#531]
```bash
atoum --version
atoum version dev-master by Frédéric Hardy
```

That seems defined in:
https://github.com/atoum/atoum/blob/master/constants.php#L9

I am not sure why it's not just:
```php
define(__NAMESPACE__ . '\version', '2.4.0');
```

**Comment by Hywan** [comment]
Yup. Not in the PHAR which are released.

**Comment by Hywan** [comment]
We could update to `2.4.0-dev` though.

**Comment by pascalchevrel** [comment]
The current behaviour doesn't seem consistent to me with a composer install (and I would expect people to install Atoum in their projects via composer, not via a phar file, even a global install via composer is more convenient than a phar file IMO because of the simple upgrade process), if I specify in my project that I want 2.4.0 it should give me the version number I installed when I launch it from the vendor profile :
```json
    "require-dev": {
        "atoum/atoum" : "2.4.0"    
    }
```

```bash
vendor/bin/atoum --version
atoum version dev-master by Frédéric Hardy
```

**Comment by jubianchi** [comment]
This is indeed a bug :/

**Comment by jubianchi** [comment]
We should issue a patch version (2.4.1) to fix the bug.

/cc @mikaelrandy @Hywan

**Comment by jubianchi** [comment]
@pascalchevrel 

> I am not sure why it's not just:

> `define(__NAMESPACE__ . '\version', '2.4.0');`

This is because atoum contains scripts updating this part (for example the phar builder) to ease matching the string we use a custom format.

**Comment by mikaelrandy** [comment]
@jubianchi @Hywan since #505, phar extension should have been automatically generated by merging PR.
But as [Travis failed)(https://travis-ci.org/atoum/atoum), maybe the generator wasn't launched and it missed some steps.

I work on the correction now

**Comment by mikaelrandy** [comment]
Ok, i understood the problem : when i have executed the ./script/git/pusher.php script, all work was pushed to my cloned repository

**Comment by jubianchi** [comment]
@mikaelrandy awesome thanks!

I'll look at the fails with the phar on travis. I don't really know why this is happening...weird fails, perhaps xdebug is breaking stuff, perhaps not...

**Comment by mikaelrandy** [comment]
I just released [2.4.1](https://github.com/atoum/atoum/releases/tag/2.4.1) with correct versioning :/

Sorry for the inconvenience

And thanks @pascalchevrel to report it quickly.

To explain the whole process : as atoum is available in rolling release and semver in same time, each time we release a new version, we change the version, create a new tag and reset version to dev-master.
This time, the script who do all this job was executed on my cloned repository, and i have generated a release without version fix.

**Comment by pascalchevrel** [comment]
Thanks for the quick action :+1:

**Comment by jubianchi** [comment]
thanks @mikaelrandy :+1:

**Comment by Hywan** [comment]
@mikaelrandy I did update the release message on Github :-).

**Comment by mikaelrandy** [comment]
@Hywan what messages ? On 2.4.1 release ?
