### ISSUE TITLE
Fatal Exception on isRegex

### ISSUE THREAD

**Issue by Fabex** [atoum/atoum#538]
Hi,

I update atoum from 2.2 to 2.4 version and now when I run my test I have this error :

```
Fatal error: Call to a member function isRegex() on null in /vendor/atoum/atoum/classes/test.php on line 801
                                                          
  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Error: Call to a member function isRegex() on null
```

I don't think it's normal given it's just a minor update and it should not be any backward break compatibility.

After research in changelog of 2.4 version it seem come from this PR : https://github.com/atoum/atoum/pull/515

**Comment by Hywan** [comment]
Hello :-),

Correct, the `isRegex` method has moved. However, it was a private method. How were you able to access it?

**Comment by Hywan** [comment]
Oh, and since it was private, this is not a BC break :-].

**Comment by Hywan** [comment]
For the record: https://github.com/atoum/atoum/pull/515/files#diff-4aabc01376cc0706dc7f0378889bcc56L1839

**Comment by Fabex** [comment]
I don't use it's in atoum core code like I say in
/vendor/atoum/atoum/classes/test.php on line 801

**Comment by Hywan** [comment]
So the variable analyzer is null, this is another error. And this is not related to #515. Please, can you provide what you did try to do? Do you have some extensions?

**Comment by Fabex** [comment]
ok I think I find the reason.
In fact we use also atoum/atoum-bundle, and our atoum-bundle was in 1.2, I update to 1.3 and it's ok
So may be you should add requirement on atoum-bundle 1.2 to require atoum < 2.4
and for 1.3 add ~2.4.

**Comment by Hywan** [comment]
Correct! Thanks for your time and congrats.

/cc @jubianchi, @stephpy, @marmotz for the Symfony bundle.

**Comment by FlorianLB** [comment]
I release a [1.2.1 version](https://github.com/atoum/AtoumBundle/releases/tag/1.2.1) that stick the atoum version to < 2.4

**Comment by Hywan** [comment]
@FlorianLB Thanks!
