### ISSUE TITLE
`\DateTimeImmutable` assertions

### ISSUE THREAD

**Issue by Spy-Seth** [atoum/atoum#547]
Atoum provide specifics assertions for `\DateTime` (nice work by the way :+1:) but there are not compatible with `\DateTimeImmutable` instance.

```
[...] mageekguy\atoum\asserters\dateTime() failed: object(DateTimeImmutable) is not an instance of \dateTime
```

There are no other asserters to works with `\DateTimeImmutable` instance. Maybe it could be a good idea to make the existing `dateTime` asserter compatibles with `\DateTimeImmutable` or by creating a dedicated asserter. It could help to spread the word of good practice.

**Comment by Hywan** [comment]
@jubianchi Why a bug? This is more a feature request, isn't it?

**Comment by Spy-Seth** [comment]
Thanks for the change. That was fast! :checkered_flag: :racehorse: :dash:

**Comment by jubianchi** [comment]
@Spy-Seth No problem ;) A new release (2.5.0) should be out soon ;)
