### ISSUE TITLE
Atoum unit tests fail under Windows 7 and PHP 7

### ISSUE THREAD

**Issue by Blackhol3** [atoum/atoum#549]
Atoum unit tests (launched with the `--test-it` option) currently fail. There is 73 failures, 4 errors and 2 exceptions with the `2.4.1` version, and one failure less with the commit [`a634452`](https://github.com/atoum/atoum/commit/a63445281bf5dfc1bc40ba10daf4fbfc2980007e). You'll find the detailed reports in [the following Gist](https://gist.github.com/Blackhol3/674b81b32ae458f9822e).

For your information, here is my configuration:

    >ver
    Microsoft Windows [version 6.1.7601]

    >php --version
    PHP 7.0.1 (cli) (built: Dec 16 2015 13:32:55) ( ZTS )
    Copyright (c) 1997-2015 The PHP Group
    Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by jubianchi** [comment]
this is weird. I won't be able to work on this issue before the next week.

I'll keep you updated.

Thanks for the report

**Comment by Blackhol3** [comment]
I've launched the Atoum unit tests again with the `2.5.1` version on PHP `7.0.2`, and it's far better. There is now just 4 failures and 1 error:

	Failure (234 tests, 1856/1874 methods, 0 void method, 18 skipped methods, 0 uncompleted method, 4 failures, 1 error, 0 exception)!
	> There are 4 failures:
	=> mageekguy\atoum\tests\units\php::test__toString():
	In file D:\vendor\atoum\atoum\tests\units\classes\php.php on line 41, mageekguy\atoum\asserters\castToString() failed: strings are not equal
	-Expected
	+Actual
	@@ -1 +1 @@
	-string(43) "C:^\WampServer^\bin^\php^\php7.0.2^\php.exe"
	+string(40) ""C:\WampServer\bin\php\php7.0.2\php.exe""
	=> mageekguy\atoum\tests\units\report\fields\runner\result\notifier\image\growl::testNotify():
	In file D:\vendor\atoum\atoum\tests\units\classes\report\fields\runner\result\notifier\image\growl.php on line 145 in case 'Success with one test, one method and one assertion, no fail, no error, no exception', mageekguy\atoum\asserters\adapter() failed: system(string(102) "growlnotify --title "Success " --name atoum --message "569fb9ad880a3" --image "569fb9ad86e02" --url ''") is called 0 time instead of 1
	[1] system(string(102) "growlnotify --title "Success " --name atoum --message "569fb9ad880a3" --image "569fb9ad86e02" --url """)
	=> mageekguy\atoum\tests\units\report\fields\runner\result\notifier\terminal::testNotify():
	In file D:\vendor\atoum\atoum\tests\units\classes\report\fields\runner\result\notifier\terminal.php on line 141 in case 'Success with one test, one method and one assertion, no fail, no error, no exception', mageekguy\atoum\asserters\adapter() failed: system(string(72) "terminal-notifier -title "Success " -message "569fb9ae7897f" -execute ''") is called 0 time instead of 1
	[1] system(string(72) "terminal-notifier -title "Success " -message "569fb9ae7897f" -execute """)
	=> mageekguy\atoum\tests\units\reports\asynchronous\coveralls::testHandleEvent():
	In file D:\vendor\atoum\atoum\tests\units\classes\reports\asynchronous\coveralls.php on line 200, mageekguy\atoum\asserters\castToString() failed: string is not equal to contents of file D:\vendor\atoum\atoum\tests\units\classes\reports\asynchronous\coveralls\resources\2.json
	-Expected
	+Actual
	@@ -1 +1 @@
	-string(501) "{"service_name":"atoum","service_event_type":"manual","service_job_id":null,"repo_token":"51bb597d202b4","run_at":"2013-05-13 10:00:00 +0000","source_files":[{"name":"foo\/bar.php","source":"<?php","coverage":[null,null,null,1,null,0,0,1]},{"name":"bar\/foo.php","source":"<?php","coverage":[]}],"git":{"head":{"id":"7282ea7620b45fcba0f9d3bfd484ab146aba2bd0","author_name":"mageekguy","author_email":"atoum@atoum.org","comitter_name":"mageekguy","comitter_email":"atoum@atoum.org"},"branch":"master"}}"
	+string(513) "{"service_name":"atoum","service_event_type":"manual","service_job_id":null,"repo_token":"51bb597d202b4","run_at":"2013-05-13 10:00:00 +0000","source_files":[{"name":"D:..\\foo\\bar.php","source":"<?php","coverage":[null,null,null,1,null,0,0,1]},{"name":"D:..\\bar\\foo.php","source":"<?php","coverage":[]}],"git":{"head":{"id":"7282ea7620b45fcba0f9d3bfd484ab146aba2bd0","author_name":"mageekguy","author_email":"atoum@atoum.org","comitter_name":"mageekguy","comitter_email":"atoum@atoum.org"},"branch":"master"}}"
	> There is 1 error:
	=> mageekguy\atoum\tests\units\test\generator::testGenerate():
	==> Error E_USER_ERROR in D:\vendor\atoum\atoum\tests\units\classes\test\generator.php on line 227, generated by file D:\vendor\atoum\atoum\tests\units\classes\test\generator.php on line 227:
	Test classes directory '\x\y\z\f.php' does not exist

For your information, the first failure strongly remind the old issue #223.

**Comment by jubianchi** [comment]
@Blackhol3 thanks! You know what, good things are coming in #559 ;)

**Comment by Blackhol3** [comment]
That's indeed some good news :) ! Thank you in the name of all Windows' user.

**Comment by jubianchi** [comment]
Closing this as everything is looking good on appveyor with PHP 7
