### ISSUE TITLE
add stubs in the require section of composer.json instead of suggest

### ISSUE THREAD

**Issue by agallou** [atoum/atoum#552]
One of the main complaints we heard about atoum was the lack of auto-completion.

Requering the atoum/stubs package fixes this problem.

But it's not a great user experience. You have to read the documentation or the composer output do that : some people still does'nt now about this package (If we look on packagist, on the 30 last days atoum/atoum has been installed 6 287 times. And the stubs package 1 025 times)

How about putting the stubs package as a requirement for atoum ? (for now it's on the suggestion section of the composer.json).

With this : 
* the user will have out of the box completion/documentation. he won't have to do anything.
* the phpdoc will still be outside atoum's repository

What do you think about this ?

**Comment by jubianchi** [comment]
atoum will stay standalone. There should be nothing in the require section. 

We'll keep stubs in the suggests. Sorry.
