### ISSUE TITLE
Integer 0 equals empty string

### ISSUE THREAD

**Issue by jubianchi** [atoum/atoum#553]
The following test passes but should not:

```php
<?php

namespace tests\units;

class stdClass extends \mageekguy\atoum
{
    public function testExempleSugar()
    {
        $this->integer(0)->isEqualTo('');
    }
}

```

**Comment by GuillaumeDievart** [comment]
@jubianchi  Maybe because you should use `isIdenticalTo` instead of `isEqual` ?

**Comment by GuillaumeDievart** [comment]
I think this test pass also:

``` php
<?php

namespace tests\units;

class stdClass extends \mageekguy\atoum
{
    public function testExempleSugar()
    {
        $this->string("atoum")->isEqualTo(0);
    }
}
```

**Comment by jubianchi** [comment]
@GuillaumeDievart indeed, this passes:

```php
<?php

namespace tests\units;

class stdClass extends \mageekguy\atoum
{
    public function testExempleSugar()
    {
        $this->integer(0)->isEqualTo('');
        $this->string('')->isEqualTo(0);
    }
}

```

Given the nature of atoum assertions (we explicitly describe the types) I think both assertions should fail.
For PHP, both assertions are true but in the atoum point of view I don't think they should.

**Comment by jubianchi** [comment]
BTW, @GuillaumeDievart you are right in that with atoum we always enforce explicitness so we should use `isIdenticalTo` here and not make this comparison implicit in atoum.
