### ISSUE TITLE
How to force ANSI colors on CLI output?

### ISSUE THREAD

**Issue by mnapoli** [atoum/atoum#558]
Hi, we are running atoum on Gitlab CI and we have a non-colorized output (probably because it runs in Docker, or some other reason). Is there a way to force atoum use ANSI colors on its output? Behat for example has a `--force-colors` option for that, I wasn't able to find one for atoum.

Thanks!

**Comment by jubianchi** [comment]
@mnapoli use the -ft (--force-terminal) flag ;)

**Comment by mnapoli** [comment]
:+1: thanks!

**Comment by jubianchi** [comment]
@mnapoli I don't know if Gitlab CI will corectly display the ANSI report as it uses several sequences to clear lines

**Comment by mnapoli** [comment]
It works! Yipee!

![](https://media.giphy.com/media/Au3kI0dobp7fq/giphy.gif)
