### ISSUE TITLE
Could not use mock on binded interface on PHP7

### ISSUE THREAD

**Issue by Spy-Seth** [atoum/atoum#560]
I'm working on a PHP7 project. And I facing on a bug on the atoum mock engine. 

I could not mock a simple interface like this:
```php
<?php

namespace MyProject;

interface FooRepositoryInterface
{
    public function load(int $id): Foo;
}
```

When I'm trying do mock it ` new \mock\MyProject\FooRepositoryInterface();`, a fatal error is triggered:
```
==> Error FATAL ERROR in /Users/spy-seth/workspace/atoum-php7-binding-bug/tests/units/FooManager.php on unknown line, generated by file /Users/spy-seth/workspace/atoum-php7-binding-bug/vendor/atoum/atoum/classes/mock/generator.php(200) : eval()'d code on line 2:
Declaration of mock\MyProject\FooRepositoryInterface::load(int $id): mock\MyProject\MyProject\Foo must be compatible with MyProject\FooRepositoryInterface::load(int $id): MyProject\Foo
> There is 1 uncompleted method:
=> MyProject\tests\units\FooManager::test_it_sould_generate_the_mock() with exit code 255:
==> output(0) ""
```

I've made a project example to reproduce the issue: https://github.com/Spy-Seth/atoum-php7-binding-bug. Here a travis build that reproduce the issue: https://travis-ci.org/Spy-Seth/atoum-php7-binding-bug/builds/104898435

**Comment by jubianchi** [comment]
@Spy-Seth indeed, atoum mock engine does not support scalar type-hint ATM...

**Comment by GuillaumeDievart** [comment]
Hi,

the problem seems to come from this line: https://github.com/atoum/atoum/blob/master/classes/mock/generator.php#L616

Need to add a blackslash before the returnType. 

I push a PR tomorrow.

**Comment by Spy-Seth** [comment]
> atoum mock engine does not support scalar type-hint ATM...

Ok I didn't find any information on the website or docs on current atoum PHP7 limitation. Maybe it could be useful to add some info on it.

**Comment by GuillaumeDievart** [comment]
No -> the fix https://github.com/atoum/atoum/pull/561

**Comment by GuillaumeDievart** [comment]
You can close this issue.

**Comment by jubianchi** [comment]
thanks @GuillaumeDievart !
