### ISSUE TITLE
Allow suppressing output of methods to stdout

### ISSUE THREAD

**Issue by pascalchevrel** [atoum/atoum#562]
This is a request for enhancement, maybe this is not a good idea but my intern spent some time looking for a way to do it in Atoum until I gave him a hint using PHP directly and not the Atoum API.

The case is this one: We needed to test a class which is used in cli mode only and has a 'report()' method which outputs data to the CLI and uses a fluent interface, so basically we had something like that:
```php
$obj = new _Foo('bar');
$obj->setSomeProperty1(1)
    ->setSomeProperty2('toto')
    ->report();
```
The report() method outputs a report of the operation and sets some properties on the object, so we test that the object has the right properties set.

Currently Atoum will output something like:
```bash
Success (1 test, 10/10 methods, 0 void method, 0 skipped method, 100 assertions)!
> There is 1 output:
=> In tests\units\pchevrel\Verif::testReport():
------------------
Report for: bar
------------------
blabla
```
It doesn't look nice and to suppress the output of the method and get a nice Atoum output we did this:

```php
$obj = new _Foo('bar');
$obj->setSomeProperty1(1)
        ->setSomeProperty2('toto');
ob_start();
$obj->report();
ob_end_clean();
```
I think it would be nice to be able to 'silence' a method, maybe with a syntax like;
```php
$obj = new _Foo('bar');
$obj->setSomeProperty1(1)
    ->setSomeProperty2('toto');
$this->suppressOutput($obj->report());
```
I just googled and it seems that other people ended up with our same output buffering trick for home made tests:
http://stackoverflow.com/questions/486181/php-suppress-output-within-a-function

What do you think?

**Comment by Hywan** [comment]
@pascalchevrel Hello :-),

Actually, the best way to do that is to use an `Output` object in your CLI program. An output is a stream. Then you are able to use a file, a socket, `/dev/null`, whatever you want, as a replacement of `/dev/stdout` for the `Output`.

I am also pretty sure that you can use the `output` to test asserter group to test the output of your program, and it will not be outputed in this case. So:
```php
$this
    ->output($obj->report())
        ->isEqualTo('…');
```
will work and will not print any on your console.

**Comment by jubianchi** [comment]
@pascalchevrel As @Hywan said, atoum has a dedicated asserter to check method outputs. You can use it to suppress outputs:

```php
<?php

namespace
{
	class foo 
	{
		public function hello() { 
                    echo 'World'; 

                    return 123;
                }
	}
}

namespace tests\units
{

	use mageekguy\atoum;

	class foo extends atoum\test
	{
		public function testMock__toString()
		{
			$this
				->given($this->newTestedInstance)
				->then
					->output(function() { $this->testedInstance->hello(); })                                            
                                            // any assertions of the strinq asserter 
                                            //->isEqualTo('World')
                                            //->contains('W')
                                            //->matches('/^W$/')
                                            // ...
			;
		}
	}
}
```

If you don't want to assert on the output, just remove the assertion and use only the `->output()` asserter it will just catch the output of your calls.
