### ISSUE TITLE
configuration from a config file, not a php one

### ISSUE THREAD

**Issue by Grummfy** [atoum/atoum#564]
Hi,
Today I speak with continuousPHP, and one of the thing they find annoying is the way we actually configure atoum. For them, it could be better if we can provide a configuration that is not a php file but a config file (json, yml, xml, ... whatever), a file in a descriptive format.

What do you think of?
For me it seems relevant. And can be easier to understand it.

ping @Hywan , @jubianchi  , @vonglasow , @agallou ...

**Comment by jubianchi** [comment]
Some times ago I worked on this extension : https://github.com/jubianchi/atoum-config-extension

It allows us to configure atoum with a YAML file.

**Comment by Grummfy** [comment]
cool, is there any reason to not put as an official one?

thanks

**Comment by Oliboy50** [comment]
:+1:
it would be really nice to have a YAML configuration out of the box (as YAML is quite the configuration standard format for every "hype" projects right now)
but I don't know if it's a good idea to maintain both types of configuration

**Comment by jubianchi** [comment]
I don't think anytime like YAML, JSON, INI or the like will ever be the default configuration format.

Plain old PHP is way more flexible than static files such as YAML or JSON. If you want to read an env. var. from a static config file it's a pain. We'll have to add too much complexity (compiler/cache, define a custom DSL for configuration, ...) in atoum to allow the same flexibility as today.

The extension provides such features but as this is not requested by too many users we'll keep what exists today.

**Comment by mikaelrandy** [comment]
@jubianchi are we open to use some external components to do stuff like this ?
I think about [Symfony Config Component](http://symfony.com/components/Config) but i'm sure a lot of other solution exists

**Comment by jubianchi** [comment]
@mikaelrandy we only allow external dependencies in extensions. atoum has always been (and will stay) fully-standalone. 

The extension I mentioned above actually uses the config and DI components from symfony.

**Comment by mikaelrandy** [comment]
@jubianchi thank for the response.

So, the extension seems to be a good solution : no overhead in the core, the PHP based config file continue to be the recommended option, but people who really want to use config files in other language could install extensions.

*My 2cts*
