### ISSUE TITLE
allow annotation engine on class

### ISSUE THREAD

**Issue by Grummfy** [atoum/atoum#572]
Hello,
I think we should add the possibility to add the annotation @engine on class and not only on method.

thanks

**Comment by jubianchi** [comment]
It already works on classes and methods:

```php
<?php

namespace {
    class foo {}

    class bar {}
}

namespace tests\units {
    use mageekguy\atoum;

    /** @engine inline */
    class foo extends atoum\test {
        public function testFoo() {
            $this->string($this->getClassEngine())->isEqualTo('inline');
        }
    }

    class bar extends atoum\test {
        /** @engine inline */
        public function testBar() {
            $this->string($this->getMethodEngine('testBar'))->isEqualTo('inline');
        }
    }
}
```

To verify this, we can edit the first test (the one on the `foo` class):

```php
<?php 
namespace tests\units {
    use mageekguy\atoum;

    /** @engine inline */
    class foo extends atoum\test {
        public function testFoo() {
            $foo->bar();
        }
    }
}
```

This will produce a fatal and stop atoum immediately: yes we are in the inline engine!

**Comment by Grummfy** [comment]
thanks, But i don't see it in the code you gave me last night ;)

**Comment by jubianchi** [comment]
@Grummfy you should clean your :eyeglasses:

https://github.com/atoum/atoum/blob/master/classes/test.php#L1612

**Comment by Hywan** [comment]
However, the same issue can be opened for `@tag`.

**Comment by Grummfy** [comment]
je vais sauter par la fenetre car je suis aveugle je pense

**Comment by jubianchi** [comment]
@Hywan and I'll close it the same way :p

https://github.com/atoum/atoum/blob/master/classes/test.php#L1608
https://github.com/atoum/atoum/blob/master/classes/test.php#L1665

**Comment by Hywan** [comment]
@jubianchi As far as I remind, `@tag`s are not inherited from class definition to method definition. So:
```php
/* @tag foo */
class C {
    /* @tag bar */
    public function f() { … }
}
```
`f` has the tag `bar`, not `foo` **and** `bar`.

**Comment by jubianchi** [comment]
@Hywan indeed, can you open an issue please, this is an easy fix, I can do it ;)

**Comment by Hywan** [comment]
@jubianchi https://github.com/atoum/atoum/issues/573
