### ISSUE TITLE
`@tag`s are not inherited from class to method definition

### ISSUE THREAD

**Issue by Hywan** [atoum/atoum#573]
`@tag`s are not inherited from class definition to method definition. So:
```php
/* @tag foo */
class C {
    /* @tag bar */
    public function f() { … }
}
```
`f` has the tag `bar`, not `foo` **and** `bar`.

**Comment by jubianchi** [comment]
Methods' tags are computed here: https://github.com/atoum/atoum/blob/master/classes/test.php#L907-L926
