### ISSUE TITLE
Potential BC break in CLI arguments management

### ISSUE THREAD

**Issue by mageekguy** [atoum/atoum#580]
Hi folks,

It seems to me that there is a BC break in CLI arguments management since 847bca7ab53a6cf4246fbef82f49874f55566684.
With this commit, i can do:
```
mageekguy@Mageekbook-Pro:~/somewhere/over/the/rainbow(master *+$%)
32|2654> php tests/units/runner.php -ulr -l
[SSSSSSSSSSSESUSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS_______________][45/45]
Failure (13 tests, 44/45 methods, 0 void method, 0 skipped method, 1 uncompleted method, 0 failure, 2 errors, 0 exception)!
…
Press <Enter> to reexecute, press any other key and <Enter> to stop...
```
Failure is irrelevant here, because the problem is the output of version 2.5.5, 2.5.1 and 2.5.0:
```
24|2644> php tests/units/runner.php --ulr -l

Error: Bad usage of -f, do php /somewhere/over/the/rainbow/tests/units/runner.php --help for more informations
Press <Enter> to reexecute, press any other key and <Enter> to stop...^C
```
Maybe versions previous 2.5.0 has the same problem, but i have not enough time to investigate more deeply.

So, i have two requests:

1. Someone else can confirm the BC break?
2. Someone can fix it rapidly if it's really a BC break?

My PHP version:

```
33|2660> php -v
PHP 5.6.18 (cli) (built: Feb 19 2016 11:12:01) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with blackfire v1.5.0, https://blackfire.io/, by SensioLabs
```

Best regards,
Fred.

Note: to test a specific commit using composer, just add `"atoum/atoum": "dev-master#<commit>"` in your `composer.json`. For example, to test with commit `847bca7ab53a6cf4246fbef82f49874f55566684`, just add `"atoum/atoum": "dev-master#847bca7ab53a6cf4246fbef82f49874f55566684`.

**Comment by jubianchi** [comment]
There is a bug in your issue : in the first command you use `-ulr` which is the short version of `--use-light-report` and in the other you use `--ulr` which is an unknown long option.

BTW, the error message is false and I'm going to fix it ;)

**Comment by mageekguy** [comment]
Ok, but why `-ulr` works with 847bca7ab53a6cf4246fbef82f49874f55566684 and not with 2.5.0?

**Comment by jubianchi** [comment]
@mageekguy I did not see any problem with `-ulr` it works on all versions on my laptop.

**Comment by mageekguy** [comment]
Need to sleep apparently…
