### ISSUE TITLE
PHAR link in README is broken

### ISSUE THREAD

**Issue by personman** [atoum/atoum#586]
The link points to http://downloads.atoum.org/nightly/atoum.phar but that's 404'd.

Maybe this is the replacement?

http://downloads.atoum.org/nightly/mageekguy.atoum.phar

**Comment by CedCannes** [comment]
+1 PHAR link is broken 

the link http://downloads.atoum.org/nightly/mageekguy.atoum.phar points a very old version of the PHAR.

@Grummfy gave me the link to the latest version : 
https://github.com/atoum/atoum/releases/tag/2.6.0
https://github.com/atoum/atoum/releases/download/2.6.0/atoum.phar

Following the README.md and the official documentation I have not managed to find the latest version.
