### ISSUE TITLE
Unable to push to master

### ISSUE THREAD

**Issue by mikaelrandy** [atoum/atoum#587]
It seems a configuration on master branch recently changed, and it's no longer possible to push to master.

But, for release process, i dont think it's a good idea to use a PR.

I think we (@rms) should be able to push to master.

ping @Hywan @jubianchi

**Comment by jubianchi** [comment]
should be ok now

**Comment by mikaelrandy** [comment]
I cannot push directly to master, due to status checks : 
```shell
~/Workspace/atoum/atoum   master  git push origin master
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 329 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: 2 of 2 required status checks are expected
To git@github.com:atoum/atoum.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:atoum/atoum.git'
```

I try to push the "Prepare 2.6.0" commit ([see the diff](https://github.com/atoum/atoum/compare/release/2.6.0)). For this change, i can create a branch, wait for CI checks before push to master, but for the commits created by the `git/pusher` script, it could be complicated.

The simplest way to keep existing release process is to allow admin to push on `master` without executing checks
Otherwise, we have to update release process to use a branch to prepare release.

@team what is your opinion ?

**Comment by jubianchi** [comment]
@mikaelrandy I added you as an admin in the org. and the push on master should be allowed to admin. Let me double-check

**Comment by jubianchi** [comment]
good now. you can push

**Comment by mikaelrandy** [comment]
Ok, you chose to let admin directly push tu master, thank you ;)
