### ISSUE TITLE
Unit test fail when I run atoum in a directory with some bash file

### ISSUE THREAD

**Issue by ivannis** [atoum/atoum#591]
Hello, I'm using atoum in my project and when I try to run atoum in a directory with some bash file, atoum try to execute this file and fail. For example:

->given(the directory structure):

```
--- some-project
------ bin
--------- atoum
------ Folder
--------- bin
------------ php-cs-fixer
--------- src
------------ Foo
-------------- FooClass.php
```
->then()
  ->when(bin/atoum -d Folder/)
  ->file(Folder/bin/php-cs-fixer)
  ->isExecuted()
;

Thanks :smile:!

**Comment by mikaelrandy** [comment]
As far as i know, you cant exclude directories. So, you should be specific while giving test dir.

`./bin/atoum -d Folder/src`

**Comment by jubianchi** [comment]
when running a directory with the -d flag, atoum will include every PHP files and every file without extension: this is why you shell script is executed.

Perhaps we should consider excluding files without extensions ? Thoughts @atoum/all ?

**Comment by mikaelrandy** [comment]
I think @ivannis want to launch atoum on a dir, with it source files, not only test files, and i think its a bad usage of atoum.
We should launch atoum execution only on folders who contains only tests files.

Additionally, 
If we have severals bundle/module/... to test, we can create an .atoum.php file to add each test dir, like this :
```php
<?php

$runner->addTestsFromDirectory("Folder/tests");
$runner->addTestsFromDirectory("Directory/tests");
$runner->addTestsFromDirectory("Module/tests");
// ...
```

And then, launch `./bin/atoum` will only execute tests.

**Comment by ivannis** [comment]
Thanks guys, I think it will be better create a .atoum file for each module within the project, as @mikaelrandy says. So, i will close the issue.

Thank you

**Comment by jubianchi** [comment]
👍 @mikaelrandy 

@ivannis be careful with creating several `.atoum.php` files: atoum will include them from the current working directory until the root of the file system so you might have two problems, depending on your project's layout:

* several configuration file might be included depending on where your modules are,
* you'll have to run atoum from the module directory (or use the `-c` flag) to tell it to use the right configuration file

**Comment by ivannis** [comment]
Thanks @jubianchi 
Now is working, I have created a global .atoum.php file in the project, following the @mikaelrandy advise, including only the source directory for each component/module:

_project/.atoum.php_
```
<?php

$runner->addTestsFromDirectory(__DIR__.'/component1/src');
$runner->addTestsFromDirectory(__DIR__.'/component2/src');
$runner->addTestsFromDirectory(__DIR__.'/component3/src');
// ...
```
and a .atoum file in each module, because this modules are splitting in a readonly repository each one. Now I have somethink like this

_project/component1/.atoum.php_
```
<?php

$runner->addTestsFromDirectory(__DIR__.'/src');
// ...
```
directory structure:

```
--- project
------ bin
--------- atoum
------ .atoum.php
------ component1
--------- bin
------------ php-cs-fixer
--------- .atoum.php
--------- src
------------ Foo
-------------- FooClass.php
------------ Tests
--------------- Units
------------------ Foo
--------------------- FooClassTests.php
.......
```
