### ISSUE TITLE
HHVM incompatibility with `directory\factory::getIterator`

### ISSUE THREAD

**Issue by Hywan** [atoum/atoum#624]
See https://github.com/atoum/atoum/pull/479#issuecomment-239820823.
Long story short: The `mageekguy\atoum\iterators\recursives\directory\factory` class is implementing `IteratorAggregate`, but the `getIterator` method expects an argument, which is wrong.

We need to fix it.

**Comment by jubianchi** [comment]
We are not working anymore on HHVM support.
