### ISSUE TITLE
array asserter & size not chainable

### ISSUE THREAD

**Issue by Grummfy** [atoum/atoum#626]
Hello,
when we do this

``` php
$this   ->array($myArray)
    ->array[ 0 ]->isEqualTo(1)
    ->size->isEqualTo(1); //OK
```

``` php
$this   ->array($myArray)
    ->size->isEqualTo(1)
    ->array[ 0 ]->isEqualTo(1); // KO => Array is undefined
```

**Comment by Oliboy50** [comment]
it seems fine to me, the syntactic sugar only works if used immediately after an array assertion

**Comment by jubianchi** [comment]
@Grummfy I'm sorry but this won't be fixed.

This behavior is expected: when you use the `->size` asserter you switch from an `->array` context to an `integer` context so array assertions are not available anymore.

Making this work would require some work around the `integer` asserter and making it linked to the `array`asserter through something like a specific `size` asserter.

What you can do is use the `hasSize` assertion which will not break the chain on the `array` asserter.
