### ISSUE TITLE
Code coverage with phpdbg

### ISSUE THREAD

**Issue by Hywan** [atoum/atoum#627]
Hello,

Since XDebug has several issues in PHP 7.x (see #551, #554), and since we are using it only for the code coverage, I propose to add a driver to support phpdbg API. This API is not documented but we can find it [by reading its code](https://github.com/php/php-src/blob/6baaa2bb1b0ec87d8c2d676da27d04370677a81c/sapi/phpdbg/phpdbg.c#L450).

PHPUnit is already using a phpdbg API: [`SebastianBergmann\CodeCoverage\Driver\PHPDBG`](https://github.com/sebastianbergmann/php-code-coverage/blob/master/src/Driver/PHPDBG.php).

Some projects are already leaving atoum because of XDebug incompatibility… Derick is helping us (see https://github.com/atoum/atoum/issues/554#issuecomment-242035976) but this is hard to produce a MWE (minimal working example).

More than that, apparently, phpdbg is really faster according to https://hackernoon.com/generating-code-coverage-with-phpunite-and-phpdbg-4d20347ffb45.

Finally, phpdbg does not do a real code coverage. This is a “line coverage” which is dumb and means nothing. Until recently, XDebug was doing the same thing but it now supports real code coverage criteria. Well, I guess that having phpdbg is better than seeing users leaving us 😃.

What do you think?

**Comment by jubianchi** [comment]
See #519.
