### ISSUE TITLE
Remove deprecated methods

### ISSUE THREAD

**Issue by jubianchi** [atoum/atoum#648]
⚠️ This should target the `3.0.0-dev` branch.

* [x] `mageekguy\atoum\asserters\dateTime::isInYear()`
* [x] `mageekguy\atoum\asserters\dateTime::isInMonth()`
* [x] `mageekguy\atoum\asserters\dateTime::isInDay()`
* [x] `mageekguy\atoum\asserters\stream::isWrited()`

**Comment by antarestupin** [comment]
Hello, I can handle this ticket. Shall anything else than the methods and the associated tests be removed?

**Comment by jubianchi** [comment]
@antarestupin no, only the method listed in this issue (and their associated tests) have to be removed. 

Feel free to open a PR once you are ready.

thanks!
