### ISSUE TITLE
Remove all code relying on `method_exists`

### ISSUE THREAD

**Issue by jubianchi** [atoum/atoum#653]
* [x] in `mageekguy\atoum\factory\builder\closure::isVariadic()`
* [x] in `mageekguy\atoum\mock\generator::getParameterType()` (line 699)
* [x] in `mageekguy\atoum\mock\generator::isVariadic()`
* [x] in `mageekguy\atoum\php\mocker\funktion::getParameterType()`
* [x] in `mageekguy\atoum\score\coverage::getDeclaringClass()`

**Comment by andyps** [comment]
Hi! Please, check pull request [#655 ]( https://github.com/atoum/atoum/pull/655)
