### ISSUE TITLE
withArguments weird behavior with DataStructures ext

### ISSUE THREAD

**Issue by tyx** [atoum/atoum#671]
|               |              |
|---------------|--------------|
| atoum version | `2.8.2` |
| PHP version   | `PHP7.0.9` |
| xDebug        | not loaded   |

We are huge fan of [ext-ds](http://php.net/manual/en/book.ds.php) (and atoum of course !) but it seems have a weird behavior with `withArguments` asserter

## Example

    <?php

    namespace atoum\shou\tests\units;

    use atoum;

    class runner extends atoum
    {
        public function testClass()
        {
            $this
            ->then
                ->mock($translatorGateway)
                    ->call('orderTranslation')
                    ->withArguments('12345', new \Ds\Set(['value']), 'fr')
                    ->once()
            ;
        }
    } 

## Actual result

    The test would be green what ever the content of my `Set`

## Expected result

    Well I hope it would assert the content of my set :D

I really don't know where to fix that behavior so let me know if I can help to fix this issue.

**Comment by Hywan** [comment]
Hello :-),

Can you provide the system under test please? What are you testing?

**Comment by tyx** [comment]
```
$content = new \Ds\Set(['value1', 'value2']);
$this->testedInstance->orderTranslation($translatorGateway, $content, 'fr');
```
where `$translatorGateway` is a mock.

The `orderTranslation` method should filter the `$content` before to call the `$translatorGateway::orderTranslation` method by passing this `$content` filtered.

But what ever the content of my Set `$content` the test is green...

**Comment by Hywan** [comment]
Can you try this please:
```php
var_dump(new \Ds\Set([1, 2, 3]) == new \Ds\Set([1, 2, 3]));
```
What's the result?

**Comment by tyx** [comment]
`bool(true)`

but

`var_dump(new \Ds\Set([1, 3]) == new \Ds\Set([1, 2, 3]));`

return true also so I guess the problem is here.

**Comment by jubianchi** [comment]
@tyx unfortunately, if the `==` operator yields wrong result, we can't do anything for now. The only yhing you can do is hook in the mock API and compare arguments manually but this is plumbing. The test will look ugly.

**Comment by tyx** [comment]
Yep I get it. I will open the issue on Ds I guess :p

**Comment by jubianchi** [comment]
See https://github.com/php-ds/extension/issues/65 where an `equals` method is suggested on collection classes. 

Such thing would not resolve the problem in atoum as we will still use the `==` operator. We should really see if we can do something like this: https://github.com/atoum/atoum/pull/254
