### ISSUE TITLE
Disable loading of parent atoum configuration files

### ISSUE THREAD

**Issue by klnjmm** [atoum/atoum#675]
Hi,

We have an web application with this directory structure (an legacy application include in a symfony app)

```
www
    |_src
        |_tests
    |_vendor
         |_atoum
    |_web
         |_legacy
              |_src
                  |_tests
              |_vendor
                   |_atoum
               .atoum.php
               .bootstrap.atoum.php
    .atoum.php
    .bootstrap.atoum.php
```

The two src directories have two differents namespaces (we can consider these two different applications) 
When I run tests from `legacy/`directory, the tests failed with this error :

`Tested class '\Namespace\Event' does not exist for test class '\Namespace\Tests\Units\Event'`

The problem is that the `www/.atoum.php` and `www/.bootstrap.atoum.php` file is loaded. If I delete (or rename) these files, my tests is OK.

How can I handle this ? I think i can rename my parent configuration files and launch `www` tests with `bin/atoum -c conf.atoum.php`.

But is It possible to disable loading of parent atoum's configuration file ?
I think that this case can also happened in monorepos project.

Thank you (discussion in french possible)

**Comment by Hywan** [comment]
Hello :-),

Your question is more: Can atoum stop after having read a first `.atoum.php` file, instead of continuing to look in parent directories? Am I correct?

I am afraid it will introduce a BC break. @jubianchi will confirm.

However, what you can do is to move all configurations in a specific directory, and yes, use the `-c` option to select the correct configuration file.

**Comment by klnjmm** [comment]
Hi Hywan,

Yes, you understand my question.
I wait confirmation of @jubianchi and if it's not possible (or not a good idea), i will do what you say.

Thank you.

**Comment by klnjmm** [comment]
You can close this issue if you want, I move all my configuration file in the same directory and use `-c` option (like Hywan said).
Thank you !

**Comment by jubianchi** [comment]
@jlnjmm @Hywan the -c option is indeed an alternative. 

I'm trying to guess how to implement such a feature but it's hard to find something clean ATM.
