### ISSUE TITLE
asserter string startWith not clear about the result

### ISSUE THREAD

**Issue by Grummfy** [atoum/atoum#676]
Hello,
here is an example of failed test 
mageekguy\atoum\asserters\phpString() failed: string(6) '616241' does not start with 6

Expected 
mageekguy\atoum\asserters\phpString() failed: string(6) '616241' does not start with integer 6
or
mageekguy\atoum\asserters\phpString() failed: string(6) '616241' does not start with int 6

test case ```$this->string('616241')->startWith(6);```

```$this->string('616241')->startWith('6'); ``` works well  ;)

**Comment by Hywan** [comment]
Hello 😃,

We could simply wrap the result in a `var_export`, I guess it will print `6` or `'6'`.

**Comment by Grummfy** [comment]
yes but in this case, the 6 will not help, because it is what is printed now ;(

**Comment by Hywan** [comment]
This is why I am proposing to wrap the result inside a `var_export` ;-).

**Comment by jubianchi** [comment]
or we should cast the `startWith` argument to string: a string cannot start with an integer (strictly speaking).

**Comment by Grummfy** [comment]
so what choice?
* var export
* string casting? => for me it seems the best solution (and the more coherent)
* error because not a string?
