### ISSUE TITLE
Windows + space in file path = Could not open input file

### ISSUE THREAD

**Issue by igordata** [atoum/atoum#677]
Hi!
Thanks for Atoum.

May be I'm doing something wrong, but I'm having a weird problem. If I run atoum on all tests in folder - it works perfectly finding all my test and running them. If I run a single file not in loop mode - it's OK. But when I'm trying to run a single file - I get this error "Could not open input file: C:\Users\igors\Documents\PhpStorm"

System: Windows 10
PHP: 7.0.14
Atoum: 2.8.2

1. Running a single file in no-loop mode.
Command: `php "C:\Users\igors\Documents\PhpStorm Projects\pinpie\tests\../vendor/atoum/atoum/bin/atoum" -c "C:\Users\igors\Documents\PhpStorm Projects\pinpie\tests\runfile.cfg.php" -f "C:\Users\igors\Documents\PhpStorm Projects\pinpie\tests\units\classes\URL.php"`
Console output:
```
> atoum path: C:\Users\igors\Documents\PhpStorm Projects\pinpie\vendor\atoum\atoum\C:\Users\igors\Documents\PhpStorm Projects\pinpie\tests\../vendor/atoum/atoum/bin/a
toum
> atoum version: 2.8.2
> PHP path: C:\Users\igors\Documents\www\server\php\php.exe
> PHP version:
=> PHP 7.0.14 (cli) (built: Dec  6 2016 15:28:01) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
> pinpie\pinpie\tests\units\URL...
[..__________________________________________________________][0/2]
...
```
So it works and do tests.

2. Running single file with -l at the end
Command: `>php "C:\Users\igors\Documents\PhpStorm Projects\pinpie\tests\../vendor/atoum/atoum/bin/atoum" -c "C:\Users\igors\Documents\PhpStorm Projects\pinpie\tests\runfile.cfg.php" -f "C:\Users\igors\Documents\PhpStorm Projects\pinpie\tests\units\classes\URL.php" -l`
Console output:
```
Could not open input file: C:\Users\igors\Documents\PhpStorm
Press <Enter> to reexecute, press any other key and <Enter> to stop...
```

As you can see, it doesn't work in that case.

I can't find a code with "Could not open input file" phrase in atoum project. May be you can fix that.
Thanks!

**Comment by igordata** [comment]
Guys?

**Comment by jubianchi** [comment]
@igordata sorry for the delay, unfortunately I can't reproduce your bug: I don't have any Windows box.

Could you help me a little bit so I can find where this behavior comes from:

* could you add a `var_dump($command);` in `classes/cli/command.php:62` just before the `if`
* could you add a `var_dump($argument, $values);` in `classes/scripts/runner.php:1363` just before the `$php->addArgument(...)`

Thanks

**Comment by igordata** [comment]
Hi! Sorry for the delay too.

I couldn't find right place you pointed me.
I'm using 2.8.2 version, but
![image](https://cloud.githubusercontent.com/assets/1877274/22194404/07fe6632-e0f7-11e6-8a60-72a28fa60f77.png)
This is the first occurance of `php->addArgument(` It is line 1269

I have total five of them in that file. All in `protected function loop()` so I decided to dump whole array `$this->argumentsParser->getValues()`

I've got that:

```
C:\Users\igors\Documents\PhpStorm Projects\pinpie\vendor\atoum\atoum\classes\scripts\runner.php:1274:
array(3) {
  '-c' =>
  array(1) {
    [0] =>
    string(71) "C:\Users\igors\Documents\PhpStorm Projects\pinpie\tests\runfile.cfg.php"
  }
  '-f' =>
  array(1) {
    [0] =>
    string(77) "C:\Users\igors\Documents\PhpStorm Projects\pinpie\tests\units\classes\URL.php"
  }
  '-l' =>
  array(0) {
  }
}
C:\Users\igors\Documents\PhpStorm Projects\pinpie\vendor\atoum\atoum\classes\cli\command.php:62:
string(335) " -f C:\Users\igors\Documents\PhpStorm Projects\pinpie\tests\../vendor/atoum/atoum/bin/atoum -- --disable-loop-mode -c "C:\Users\igors\Documents\PhpStorm Projects\pinpie\tests\runfile.cfg.php" -f "C:\Users\igors\Documents\PhpStorm Projects\pinpie\tests\units\classes\URL.php" --score-file "C:\Users\igors\AppData\Local\Temp/atoum.score""
Could not open input file: C:\Users\igors\Documents\PhpStorm
Press <Enter> to reexecute, press any other key and <Enter> to stop...C:\Users\igors\Documents\PhpStorm Projects\pinpie\vendor\atoum\atoum\classes\cli\command.php:62:
string(335) " -f C:\Users\igors\Documents\PhpStorm Projects\pinpie\tests\../vendor/atoum/atoum/bin/atoum -- --disable-loop-mode -c "C:\Users\igors\Documents\PhpStorm Projects\pinpie\tests\runfile.cfg.php" -f "C:\Users\igors\Documents\PhpStorm Projects\pinpie\tests\units\classes\URL.php" --score-file "C:\Users\igors\AppData\Local\Temp/atoum.score""
```

As you can see, a path to atoum executable somehow got rid of quotes.
I tried a workaround: in `classes/cli/command.php` in `public function __toString()` I added a simple if:

```PHP

				if ($option == '-f'){
					$command .= ' "' . $value.'"';
				}else {
					$command .= ' ' . $value;
				}
```
so now it looks like this:
```PHP
	public function __toString()
	{
		$command = '';

		foreach ($this->options as $option => $value)
		{
			$command .= ' ' . $option;

			if ($value !== null)
			{
				if ($option == '-f'){
					$command .= ' "' . $value.'"';
				}else {
					$command .= ' ' . $value;
				}
			}
		}
...
```

And it works.

I don't know should you accept that kind of solution, or there is some special place where -f option is formed. I didn't found it. I tried to do something around classes/scripts/runner.php:1363, but didn't succeed.

If you say that is correct place, or if you will provide a whole line of code, I'd be happy to find, fix, and prepare pull request for your project and became a part of it.

**Comment by Grummfy** [comment]
@jubianchi @Hywan or @mikaelrandy any thought on that one? the fix seems easy but not sure about the consequences
