### ISSUE TITLE
datetime asserter & timezone

### ISSUE THREAD

**Issue by pgoergler** [atoum/atoum#680]
hi,

It could be great to compare \DateTime

for now with :
```
$paris =  new \DateTime('2017-01-18 00:00:00+0100');
$utc =  new \DateTime('2017-01-17 23:00:00+0000');
```

```datetime($paris)->isEqualTo($utc)``` fail ❌  
but $paris and $utc represent the same time but in a other timezone.

```integer($paris->getTimestamp())->isEqualTo($utc->getTimestamp())``` pass ✔️ 

Maybe ```datetime($paris)->isEqualTo($utc)``` should return the same result as: 
```integer($paris->getTimestamp())->isEqualTo($utc->getTimestamp())```

**Comment by jubianchi** [comment]
@pgoergler Thanks for your bug report.

Can you tell me which PHP version you are running because I'm writing a unit test to cover your case and everything is fine:

```php
public function testIsEqualTo(atoum\locale $locale)
{
    $this
        ->given(
            $this->newTestedInstance
                ->setLocale($locale),
            $this->calling($locale)->_ = $notEqual = uniqid(),
            $now = date(DATE_ISO8601)
        )
        ->if($this->testedInstance->setWith(new \dateTime($now)))
        ->then
            ->object($this->testedInstance->isEqualTo(new \DateTime($now)))->isTestedInstance
        ->given(
            $nowUTC = '2017-01-17 23:00:00+0000',
            $nowUTCPlusOne = '2017-01-18 00:00:00+0100'
        )
        ->if($this->testedInstance->setWith($value = new \dateTime($nowUTC)))
        ->then
            ->object($this->testedInstance->isEqualTo(new \dateTime($nowUTCPlusOne)))->isTestedInstance
        ->if($this->testedInstance->setWith($value = new \dateTime($nowUTCPlusOne)))
        ->then
            ->object($this->testedInstance->isEqualTo(new \dateTime($nowUTC)))->isTestedInstance
    ;
}
```

I'll push my branch so you can see the actual results.

**Comment by jubianchi** [comment]
@pgoergler as you can see here: https://github.com/atoum/atoum/pull/681

Everything is green.

**Comment by pgoergler** [comment]
Indeed i just relaunch my tests and it pass, i don't know what i've done before.
Sorry.

**Comment by jubianchi** [comment]
@pgoergler thanks for your feedback!
