### ISSUE TITLE
Test failure with 7.1.2RC1

### ISSUE THREAD

**Issue by remicollet** [atoum/atoum#683]
Discovered in Fedora QA since updated from 7.1.1 to 7.1.2RC1
https://apps.fedoraproject.org/koschei/package/atoum?collection=f26

```
Declaration of mageekguy\atoum\asserters\castToArray::setWith($value) must be compatible with mageekguy\atoum\asserters\phpArray::setWith($value, $checkType = true)

Declaration of mageekguy\atoum\mock\stream\invoker::offsetSet($call, $mixed) must be compatible with mageekguy\atoum\test\adapter\invoker::offsetSet($call = NULL, $mixed = NULL)
```

PHP Release Managers have been informed about this, under investigation to see if must be fixed in PHP 7.1.2 or if this is a valid error.

**Comment by Hywan** [comment]
Thanks!

**Comment by remicollet** [comment]
FYI, the RM choose to revert the guilty change, so 7.1.2RC1 (which will be announced later today) will work as expected (see above link, back to green in Fedora QA, 7.1.2-0.1.RC1 was the old tag, 7.1.2-0.2.RC1 is the new one))

So closing for "for information" issue, and I will continue to monitor future changes.
