### ISSUE TITLE
A comment starting with the word ignore cancels the annotation @ignore

### ISSUE THREAD

**Issue by CedCannes** [atoum/atoum#684]
Classes marked as ignore are not ignored because of the content of the comment.
```
/**
 * @ignore
 * Ignore start this comment and causes problems
 */

```

```
/**
 * @ignore
 * This comment does not start with the word ignore causes no problems
 */
```

```
/**
 * @ignore
 * ignore
 * alone the word causes no problems 
 */
```

> atoum version: 2.8.2
=> PHP 7.0.13-0ubuntu0.16.04.1 (cli) ( NTS )
=> Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
=>     with Zend OPcache v7.0.13-0ubuntu0.16.04.1, Copyright (c) 1999-2016, by Zend Technologies
=>     with blackfire v1.11.1, https://blackfire.io, by Blackfireio Inc.

**Comment by Hywan** [comment]
What is the correct expected syntax for you?

**Comment by CedCannes** [comment]
I expect that a test class with an "ignore" annotation will be ignored.
Even this one:
```
/**
 * @ignore
 * Ignore start this comment and causes problems
 */
```
