### ISSUE TITLE
error_log cause unknow error

### ISSUE THREAD

**Issue by CedCannes** [atoum/atoum#685]
```
class TestErrorLog
{
    public function runErrorLog()
    {
        error_log('message'); // causes error
//        error_log('message', 3, '/tmp/file.txt'); //  doesn't cause error
        return true;
    }
}
```
```
> There is 1 error:
=> Tests\Units\TestErrorLog::testErrorLog():
==> Error UNKNOWN in /home/cedric/scratch/Tests/Units/TestErrorLog.php on unknown line, generated by unknown file:
message
```

 Error UNKNOWN in /Tests/Units/Twitter/TestErrorLog.php on unknown line, generated by unknown file:

This is the error I can see if I test a method containing the error_log function in mode 0. 
If the parameter $message was not displayed it would be difficult to find the error.
As a temporary solution, I mock the native function with
`->given($this->function->error_log = true)`

>atoum version: 2.8.2
=> PHP 7.0.13-0ubuntu0.16.04.1 (cli) ( NTS )
=> Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
=> with Zend OPcache v7.0.13-0ubuntu0.16.04.1, Copyright (c) 1999-2016, by Zend Technologies
=> with blackfire v1.11.1, https://blackfire.io, by Blackfireio Inc.

**Comment by jubianchi** [comment]
@CedCannes sorry we can't do anything about this: `error_log` does not produce any backtrace so atoum can't guess from where it was called this is why it display a generic error reporting.

As you suggested, you can mock `error_log` in your test thus removing the reported errors. This solution has a nice side-effect: now you can verify that `error_log` was correctly called when testing for error cases.

**Comment by CedCannes** [comment]
Thanks for your answer @jubianchi.
Do you think that this particular case should be included in the documentation.
"If you get an unknow error check if you have an error_log ? " :wink:

**Comment by Hywan** [comment]
@CedCannes Absolutely. Maybe in a FAQ. Please open an issue in the documentation bug tracker!
