### ISSUE TITLE
Results differs from atoum to browser

### ISSUE THREAD

**Issue by funilrys** [atoum/atoum#711]
After trying to find where my problem was, I intentionally create a bug in my code to check the results from Atoum to browsers. 
I found that the results are not the same ...

## Example

```php
// I have the following array after 
// checking if the directories exist under a predefined directory.

// Format : array('directory' => status)
array (size=3)
  'styles' => boolean true
  'js' => boolean true
  'images' => boolean false
```

## Browser
This is what the browser give me which is coherent with the previous array:
![deepinscreenshot20170417123545](https://cloud.githubusercontent.com/assets/14127285/25086866/5cc47f06-236b-11e7-93c3-b2bf72d87123.png)

## Atoum
```
> There is 1 failure:
=> Core\tests\units\Files::testCheckDir():
In file /home/funilrys/public_html/funombi/Tests/Core/Files.php on line 73, mageekguy\atoum\asserters\exception() failed: message 'The directory 'public/styles' is not found' is not identical to 'The directory 'public/images' is not found'
```

## Versions
Atoum : 3.0 
    SHA-1: d5ef51a916a39651febb3957944888560362f6fd
    Downloaded with composer

```
$ php -v
PHP 7.1.4 (cli) (built: Apr 11 2017 18:32:05) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.4, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans
```

**Comment by mikaelrandy** [comment]
Hello,

As atoum is a **unit** test framework, I think you have a specific use case using atoum for **integration** tests.
Can you give us the tested code, and the corresponding test code ?

**Comment by jubianchi** [comment]
@funilrys any feedback ?

Without more detail, I'll have to close the issue. Sorry.

**Comment by funilrys** [comment]
@jubianchi @mikaelrandy 

Code: https://github.com/funilrys/funombi/blob/master/Core/Files.php#L65
Test: https://github.com/funilrys/funombi/blob/dev/Tests/Core/Files.php#L82

**Comment by Hywan** [comment]
@funilrys Is the same user that executes your HTTP server, than your tests? Is it the same permissions?

**Comment by funilrys** [comment]
@Hywan  Yes same user it's not a permission I took half a day to check that part ...

**Comment by funilrys** [comment]
Fixed, sorry it was a code side issue! 

Thanks again and keep up the good work :+1: :wink: 

Closing.
