### ISSUE TITLE
improvement : $this->testedClass:MY_CONST

### ISSUE THREAD

**Issue by Grummfy** [atoum/atoum#717]
Hello,
a nice feature could be to have this behaviour :

$this->testedClass::MY_CONST or something similar to access to the constant of the class we test.

**Comment by Hywan** [comment]
Hello,

It already works 😄.

**Comment by Grummfy** [comment]
Well I was not able to use it without error :(

> => tests\units\App\Services\Parking\GateAliasService::testGenerateAliasCode():
> ==> Error FATAL ERROR in /home/jvb/workspace/newBePark/nb-admin/tests/units/App/Services/Parking/GateAliasService.php on unknown line, generated by file /home/jvb/workspace/newBePark/nb-admin/tests/units/App/Services/Parking/GateAliasService.php on line 22:
> Uncaught Error: Undefined class constant 'TYPE_PARTNER'
> ==> Error 
> 
> ERROR in /home/jvb/workspace/newBePark/nb-admin/tests/units/App/Services/Parking/GateAliasService.php on unknown line, generated by file /home/jvb/workspace/newBePark/nb-admin/tests/units/App/Services/Parking/GateAliasService.php on line 22:
> Undefined class constant 'TYPE_PARTNER'
> > There is 1 uncompleted method:
> => tests\units\App\Services\Parking\GateAliasService::testGenerateAliasCode() with exit code 255:
> ==> output(0) ""
>

**Comment by Hywan** [comment]
I have just tested within the `atoum\php\extension` test suite, and it works :-/. That's a dumb test, but it works.

**Comment by Grummfy** [comment]
here is an example (with last version of atoum)
https://gist.github.com/Grummfy/fdd0c75507b2624151a6df4b7b688b39

**Comment by mikaelrandy** [comment]
It works with `$this->testedInstance`, but not with `$this->testedClass`.
See my answer on @Grummfy gist

**Comment by Grummfy** [comment]
thanks. I will document it  ;)

**Comment by mikaelrandy** [comment]
But it's still a question around this difference.
Do we have to allow `$this->testedClass::CONST` usage ?

Without any clue on the complexity, I think it should work.

**Comment by Grummfy** [comment]
it's just that for me it's more logic to use the class and not the instance ... but if it's documented, it's ok

**Comment by jubianchi** [comment]
@Grummfy @mikaelrandy `$this->testedClass` refers to an asserter (`mageekguy\atoum\asserters\testedClass`) this is why you get an error (Undefined constant).

Here are the two valid ways to access constants from the tested class:

```php
<?php
namespace
{
	class Foo
	{
		const A = 'a';
	}
}
namespace tests\units
{
	class Foo extends \atoum\test
	{
		public function testFoo()
		{
			$this
				->given($this->newTestedInstance())
				->then
					->string($this->getTestedClassName()::A)->isEqualTo('a')
					->string($this->testedInstance::A)->isEqualTo('a')
			;
		}
	}
}
``
