### ISSUE TITLE
Cannot use 'object' as class name as it is reserved

### ISSUE THREAD

**Issue by trasher** [atoum/atoum#723]
Hello,

Since today, I get failures on travis builds on php nightly:

```
==> Error FATAL ERROR in /home/travis/build/glpi-project/glpi/tests/units/Item_Devicesimcard.php on unknown line, generated by file /home/travis/build/glpi-project/glpi/vendor/atoum/atoum/classes/asserters/object.php on line 7:

Cannot use 'object' as class name as it is reserved
```

The PHP version is:
PHP 7.2.0-dev (cli) (built: Jun 29 2017 16:29:00) ( ZTS )

**Comment by remicollet** [comment]
Related to 
* https://wiki.php.net/rfc/object-typehint
* http://git.php.net/?p=php-src.git;a=commitdiff;h=8e10c9d37398f0f3eece85fca713f19d11cdfb32

> "object" (in any case) can no longer be used as a class name.

**Comment by remicollet** [comment]
I confirm, fix work perfectly, thanks.

**Comment by jubianchi** [comment]
Thanks @remicollet and @trasher!
