### ISSUE TITLE
exception asserter : cannot use `isInstanceOf` on interface

### ISSUE THREAD

**Issue by tyx** [atoum/atoum#730]
Hello,

The doc misses a point on the asserter `exception::isInstanceOf`. The current implementation checks also that the class given as argument is extending the `Exception` class : https://github.com/atoum/atoum/blob/9a063587cc39e47b6bd50b0adb994400d27ca679/classes/asserters/exception.php#L66

Before fixing the doc I want to discuss it ;)

I should admit I would rely on interface in this asserter, so I'm wondering if this extra check is really needed ? Or should we add an extra asserter method to really check on `Exception` inheritance like `isExceptionInstanceOf` ?

Or you might have an extra tips to achieve my test ? (ensure exception is instance of an interface)

**edit: extra idea**

Like  `message` asserter we could add an `object` asserter that rely only on the exception like a standard object. So we could do `$this->exception(/***/)->object->isInstanceOf(MyInterface::class)`

**Comment by jubianchi** [comment]
@tyx thanks for reporting this!

I added the bug label because the `exception::isInstanceOf` should accept anything `instanceof` understands, an class name or an interface.

The code actually has a bug. I'm going to fix it. PR is coming.

**extra note**

The feature you suggest is more or less already available. Here is an example:

```php
<?php

class bar extends atoum {
    public function testLogout()
    {
        $this
            ->given($this->newTestedInstance())
            ->then
                ->exception(function() { $this->testedInstance->logout(); })->isInstanceOf(\Throwable::class)
                ->object($this->exception)->isInstanceOf(\exception::class) // Here, $this->exception refers to the last captured exception
        ;
    }
}
```

**Comment by tyx** [comment]
Thanks !

And I like this notation ! I was using `$this->exception()->getValue()` for now and was not satisfied ;)
