### ISSUE TITLE
Uncompleted methods: failure with red bar and exit code 0

### ISSUE THREAD

**Issue by vdechenaux** [atoum/atoum#732]
Hi,

I have a problem with my tests:
![atoum](https://user-images.githubusercontent.com/1501825/29881007-a77abb7a-8da9-11e7-9133-5e6067117691.png)

3 methods have a PHP error ( calling a method on null variable ) and atoum stops with code `0`.
My CI is green but theses tests are failing since 3 weeks :sob: 

Thanks

**Comment by jubianchi** [comment]
@vdechenaux could you please tell me which atoum version you are using?

I'm trying to reproduce the bug and, reproducing the error you mentioned (calling a method on a null variable) does make atoum exit with an error code (`1`).

**Comment by vdechenaux** [comment]
We are using `3.1.1` + `atoum/ruler-extension` in `1.3.0`

**Comment by jubianchi** [comment]
@vdechenaux ok.

Any chance there is something consuming the error/exception and calling `exit` or `die(int)` somewhere?

If yes, I have a patch ready for PR.

**Comment by vdechenaux** [comment]
Oh, maybe!
I check that with xdebug tomorrow morning.

Thanks!

**Comment by jubianchi** [comment]
@vdechenaux never mind... there is an inconsistency in atoum: red bar does mean there is something wrong.

Fixing it: the same rule will apply on the result bar and the exit code.
