### ISSUE TITLE
Question : why is composer autoload not loaded ?

### ISSUE THREAD

**Issue by guiled** [atoum/atoum#749]
I can figure out why composer autoload script is not used while it is explained in the doc http://docs.atoum.org/fr/latest/configuration_bootstraping.html#autoloader-file

Here are 2 examples :
`php ~/bin/atoum.phar -d ./test/`
**--> errors**
`php ~/bin/atoum.phar -d ./test/ -af vendor/autoload.php`
**--> success**

As you can see, when I specify to use an autoload file placed exactly where atoum should find it by default. I also tried to use `.autoload.atoum.php` in the current directory

So, is there anything I am doing wrong ?

Thank you

**Comment by Grummfy** [comment]
hello,
can you tell me the version of atoum you are using.
Is there any help with php ~/bin/atoum.phar ++verbose?

it's seems you are doing it properly

**Comment by guiled** [comment]
Thank you for your consideration.
Here are some CLI results. Do you need more information ?

```
$ php ~/bin/atoum.phar -v
atoum version 3.2.0 by Frédéric Hardy 
```

```
atoum -d test/ ++verbose
Using -d test/ ++verbose arguments…
Using '/var/folders/yz/b9xhhc4s25dg5l53fym9d1s00000gn/T/8a630b2a26d9a326a117777b1ca1d6a3.atoum.cache' autoloader cache file…
```

**Comment by Grummfy** [comment]
bug confirmed! Nice one ;) I will write the descriptions

**Comment by Grummfy** [comment]
To reproduce it, I have using the phar archive from the last release from github. place myself in the directory where I got a .atoum.php & a .autoloader.atoum.php files. When I use the composer version of atoum from the vendor directory, the .autoloader.php file was charged according the ++verbose. Not with the phar archive (launched from the same directory, but the phar archives was somewhere else).

When I move the the phar archive in the project directory: 0 issue.
When I move the the phar archive in the parent of the project directory: same issue.

**Comment by guiled** [comment]
👍 I didn't figure that it was a "global phar" bug
Thank you @Grummfy

**Comment by Grummfy** [comment]
thanks to report it.

things I don't test, using atoum installed in a composer and try to do the same test.
