### ISSUE TITLE
CLI: Help text options are hard to read

### ISSUE THREAD

**Issue by sirbrillig** [atoum/atoum#760]
I know this is my opinion, but I find the center-alignment of the help text options (when running `atoum --help`) difficult to read. It's also a pattern I've never seen in other CLI tools which are typically left-aligned and wrap in columns.

The CLI help text also has no maximum line-length and when it wraps it's hard to read. It would be better to wrap within columns.

Finally, the default colors for the options have poor contrast on a black background. The common pattern I've seen in other CLI tools is to not colorize the help text.

For example here's my help text:

<img width="1440" alt="screen shot 2017-10-09 at 7 00 45 pm" src="https://user-images.githubusercontent.com/2036909/31361988-2fd061b6-ad24-11e7-8b47-89d1ece11f3c.png">

Compared to, for example, Jest:

<img width="692" alt="screen shot 2017-10-09 at 7 01 40 pm" src="https://user-images.githubusercontent.com/2036909/31362019-53c9e754-ad24-11e7-95e8-89027b55738d.png">

**Comment by Hywan** [comment]
I totally agree with this, and it a discussion topic that came several times already.

@jubianchi, @Grummfy, @vonglasow Do you agree to remove this mid-alignment?

**Comment by vonglasow** [comment]
If we adopt something which is readable and clean it's ok for me to change.
