### ISSUE TITLE
CLI: Help text uses full and incorrect path name to binary

### ISSUE THREAD

**Issue by sirbrillig** [atoum/atoum#761]
The help text `atoum --help` by default prints the full path name to the binary, which to me seems unnecessary and adds noise to the output (e.g.: `Usage: /Users/payton/Code/automattic-sandbox/bin/tests/payments-suites/atoum [path/to/test/file] [options]`).

Furthermore, the path isn't even correct. It appears to be the full path to the current working directory rather than to the directory where the binary is located. (In this case, the binary is located in `vendor/bin`).

More correct would be the relative path to the binary, in this case: `vendor/bin/atoum [/path/to/file] [options]`.

**Comment by Hywan** [comment]
You're right! #770 addresses it.
