### ISSUE TITLE
Assertion failures show full path for assertion without assertion name

### ISSUE THREAD

**Issue by sirbrillig** [atoum/atoum#765]
Assertion failures use full paths for the assertion, which seems like it is maybe not necessary, especially for common assertions (e.g.:  `isEqualTo()` produces `mageekguy\atoum\asserters\phpString() failed: strings are not equal`). 

Furthermore, it does not use the name of the assertion (`isEqualTo`) anywhere in the error.

**Comment by Hywan** [comment]
Thanks!

#771 fixes the namespace thing. However, the `isEqualTo` asserter name is not present because a more relevant error is given (here: “strings are not equal”). Maybe we should consider adding the asserter name too. Thoughs @atoum/core?

**Comment by jubianchi** [comment]
@Hywan adding the assertion name (i.e `isEqualTo`)  may not be relevant.

Imagine we create an alias for `isEqualTo`: `$this->from('string')->use(`'isEqualTo')->as('is')` Then, in the tests, the developper may write `$this->string($foo)->is('foo')` but the error message will display something like `mageekguy\atoum\asserters\phpString::isEqualTo() failed: strings are not equal`.

It is :
* confusing : the user never used (directly) the `isEqualTo`
* redundant : the failure message and the asserter give the exact same information

Moreover, imagine what the message could be when we used "composed" assertions (for example on mocks) : `$this->mock($mock)->call('foo')->withArguments($bar, $baz)->once()`. When there is a fail, what should we display here ?

* `mageekguy\atoum\asserters\mock()` ?
* `mageekguy\atoum\asserters\mock::call()` ?
* `mageekguy\atoum\asserters\mock\call::withArguments()` ?
* `mageekguy\atoum\asserters\mock\call::once()` ?

**Comment by Hywan** [comment]
I agree, that's a difficult topic.

Maybe it's just better to add an excerpt of the test case, with an arrow pointing to the line, with a beautiful message. It is more visual, and it links the error mesage to the code of the test, win-win?

**Comment by Hywan** [comment]
I mean, something like:

```
… string() failed: strings are not equal

--

  code
→ code string($foo)->isEqualTo($bar)
  code

--

here is the diff:

…

```

**Comment by jubianchi** [comment]
@Hywan indeed, it would be nice.

<img width="1035" alt="capture d ecran 2017-10-10 a 09 50 44" src="https://user-images.githubusercontent.com/327237/31389945-899143ec-ada0-11e7-94cb-6d430a2c0809.png">

**Comment by Hywan** [comment]
❤️
