### ISSUE TITLE
Property access `$this->newTestedInstance` has an effect

### ISSUE THREAD

**Issue by sirbrillig** [atoum/atoum#766]
This is just my opinion, but it seems confusing that `$this->newTestedInstance` has an effect inside`given()`, even though it's just a property access rather than a function call, and the documentation seems to imply that everything passed to `given()` is ignored.

Why is it not `$this->newTestedInstance()` or, maybe even better with a verb, `$this->createNewTestedInstance()`?

**Comment by Hywan** [comment]
Every argument passed to `given` is not ignored, it just has no effect inside the `given` method (which is not really a method, it's just a keyword here).

I reckon you can use `$this->newTestedInstance()` with parenthesis. I have to admit I never use this feature though. Most of the time, “test APIs” can be used with or without parenthesis.

**Comment by mageekguy** [comment]
Keywords like `given()`, `if()` and `then()` are just decoration.
You can do anything between parenthesis.
For example, these two versions of the same test are functionally identical:

```
->given(
   $this->newTestedInstance,
   $foo = new \mock\foo
)
->if(
   $this->calling($foo)->getBar = $bar = new \mock\bar
)
->then
    ->object($this->testedInstance->getBar($foo))
       ->isEqualTo($bar)
;

$testedInstance = $this->newTestedInstance;
$this->calling($foo = new \mock\foo)->getBar = $bar = new \mock\bar;
$this->object($testedInstance->getBar($foo))->isEqualTo($bar) 
```

Moreover, if a constructor has no argument, you can do `$foo = new foo` without parenthesis.
See `$this->newTestedInstance` (or `$this->newTestedInstance($arg, $otherArg, …)` as syntactic sugar, not like a class property.

**Comment by jubianchi** [comment]
@mageekguy said everything :) I have nothing to add here :)

**Comment by sirbrillig** [comment]
Ah, I didn't realize it could also be used with parenthesis! That is much more clear in my opinion. Thank you. I was just following the documentation which I don't think mentions that.

> Finally, one of atoum's goals is to simplify writing of tests, and if the developper must add () after $this->newTestedInstance without any significant value, i'm not sure that atoum simplify its job.

I totally agree that simplicity and avoiding unnecessary boilerplate is very important, but I feel that we must always be careful not to sacrifice readability. To my eye, when I see `$this->newTestedInstance` I read it as a property, `newTestedInstance`. My reasons are:

- Function calls typically end with parenthesis (with the exception of constructors, as you correctly pointed out, but at least they are prefixed by `new`). A function name _without_ parenthesis reads, to me, as a reference to the function.
- The name is a noun, and does not include any verbs. Function names typically include verbs because they take an action.

I haven't looked at the implementation of `newTestedInstance` to see how it operates, but I imagine it must use some special tricks (or perhaps it's built into the parser rather than being PHP code) to be able to take an action without parenthesis?

I wouldn't suggest changing the current implementation, since that would break backwards compatibility, but I do appreciate the discussion 🙇 , and it would be nice (for me) if the documentation at least used the parenthesis version of the function.

I apologize if I'm not understanding something correctly about the design of this feature.

**Comment by sirbrillig** [comment]
To add one more way of looking at my concern: 

As I understand it, everything in `given()` is a statement. Therefore, everything in `given()` should be a valid statement inside or outside `given()`, but if I see this on a line by itself, I would assume it is a noop:

```php
$this->newTestedInstance;
```

**Comment by jubianchi** [comment]
@sirbrillig I totally agree with you. An "orphan" `$this->newTestedInstance;` will look like a noop.

atoum allows us to choose how we want to write tests. It supports both notation (with or without parens) everywhere. Not using parens inside a `given()` seems readable.

We should indeed add a notice to the documentation (cc @atoum/docs).

> I haven't looked at the implementation of newTestedInstance to see how it operates, but I imagine it must use some special tricks

atoum heavily relies on PHP's magic methods to accomplish this: `__get`in the case of `$this->newTestedInstance`.  Everything in the public API (i.e all assertions, keywords, etc) uses magic methods (`__get`, `__set`, `__invoke`, `__call`).

**Comment by sirbrillig** [comment]
👍 cool! Thanks for the explanation. I wasn't aware that the no-parenthesis syntax was used everywhere (still new to the project, sorry!). In that case, I agree that maybe just surfacing that somewhere near the beginning of the guide could help confused people like myself. 😄

**Comment by jubianchi** [comment]
> still new to the project, sorry!

Don't be sorry, we are here to help ;)

>  I wasn't aware that the no-parenthesis syntax was used everywhere

It very useful when you write assertions like `$this->boolean($foo)->isTrue` or `$this->array($foo)->isEmpty`.

Everything in atoum you can call without any arguments should also be callable without parens ;)
