### ISSUE TITLE
s/uncompleted/incomplete/

### ISSUE THREAD

**Issue by Hywan** [atoum/atoum#775]
Everywhere we use the term `uncompleted` (e.g. `uncompletedMethod`). It is a typo. The correct word is `incompleted`.

**Comment by christophermoura** [comment]
Hi there!

I'd like to contribute on this issue.

**Comment by jrwarwick** [comment]
English, riddled with irregularities as it is, would recognize "incomplete" as a more correct form than "incomlpeted". Even for past tense. "These tasks are incomplete" and "i found that all of the tasks were incomplete" both sound correct. Moreover, sometimes, uncompleted may indeed be perfectly correct!
https://english.stackexchange.com/questions/212119/why-do-we-say-incomplete-but-uncompleted

I apologize if this comes across as pedantic. In any case, the meaning will be clear.

**Comment by torbenbru** [comment]
did a pull request to fix all the 'typos'
not quite sure why some builds are failing though. Would love some review!
#776

**Comment by Hywan** [comment]
If “uncompleted” is correct (thanks @jrwarwick for this useful note!), I think the PR from @torbenbru is not needed. Thoughts?
