### ISSUE TITLE
Questions about the native function mocking system

### ISSUE THREAD

**Issue by R11T** [atoum/atoum#779]
Hi,

First of all, thanks for your awesome tool, my company uses it in a daily basis, it's more than useful.

Sadly, my team and I face a problem regarding the mock of native function. Let's see it : 
```php

// Foo/A.php
namespace Foo;

class A
{
  public static function funcOne()
  {
    return file_exists(static::funcTwo());
  }
  
  public static function funcTwo()
  {
      var_dump('funcTwo called');
      return '/foo/bar';
  }
}

// Tests/Units/Foo/A;
namespace Tests\Units\Foo;

class A
{
  public function testFuncOne()
  {
    $class = $this->testedClass->getClass();
    $this->function->file_exists = true;
    $this->boolean($class::funcOne())->isTrue();
  }
}
```

The result is green but outputs « funcTwo called ».

It seems that I don't fully understand its behavior. I thought that mocking system completely bypasses normal call and thereby this normal call is not executed. Do I miss something ?
What is the *good* method to test this method ? (*given I can't question the relevance of the static method yet*)

Thanks.

**Comment by Hywan** [comment]
Hello,

The constant and function mock engines require your SUT (system under test, here the class `A`) to be in a namespace.

It relies on the “bubble” lookup PHP performs to find the appropriate symbols. Consider the following code:

```php
namespace A\B;

class C
{
    public function f()
    {
    }
}

**Comment by R11T** [comment]
Ooops. Obviously, A and Tests\Units\A are in a namespace. Sorry, i'll fix my example.

**Comment by Hywan** [comment]
atoum version 3.2 raises an error when trying to use the function mock engine within unnamespaced code, https://github.com/atoum/atoum/blob/master/CHANGELOG.md#320---2017-09-07.

**Comment by jubianchi** [comment]
@R11T mocking a function (in your case fil_exists) will prevent applying the real function behavior but will not prevent PHP from evaluating expressions passed as arguments.

In your case the argument of file_exists is the teturn value of another dunction call which outputs something via var_dump.

**Comment by R11T** [comment]
> […] will prevent applying the real function behavior but will not prevent PHP from evaluating expressions passed as arguments.

Thanks for your answer. I feared something like that. In that case, what are your testing recommendations (design, etc.), in order to guide our future refacto. ?

**Comment by jubianchi** [comment]
@R11T it really depends on what your are trying to test.

The example you provided describes the worst possible case for atoum: you are testing static methods calling other static methods. 

We can't actually mock static calls with atoum, it does not have the required tools. 

If we were in a more common case, you could test using a mock of `\Foo\A` something like that :

```php
<?php

namespace Foo
{
    class A
    {
        public function funcOne()
        {
            return file_exists($this->funcTwo());
        }

        public function funcTwo()
        {
            var_dump('funcTwo called');
            return '/foo/bar';
        }
    }
}

// Tests/Units/Foo/A;
namespace Tests\Units\Foo
{
    use atoum;

    class A extends atoum
    {
        public function testFuncOne()
        {
            $class = new \mock\Foo\A();
            // We stub funcTwo so that it always returns a random path
            // It won't output anything because var_dump will never be called
            $this->calling($class)->funcTwo = $path = uniqid();

            // We stub file_exists so that it always return true for our random path
            $this->function->file_exists = true;

            // We run an assertion on the return value of funcOne
            $this->boolean($class->funcOne())->isTrue();

            // We verify funcTwo was actually called once
            $this->mock($class)->call('funcTwo')->once();

            // We verify file_exists was actually called once
            $this->function('file_exists')->wasCalledWithArguments($path)->once();
        }
    }
}
```

We generally do not advise to test a class using a mock. Mocks can have side effects. So another thing to explore is either mocking `var_dump` to avoid the "unexpected" output : 

```php
<?php

// This will prevent var_dump from doing anything
$this->function->var_dump->doesNothing;
```

But sometimes, an output is actually generated and it comes from something that we can't mock (`echo` for example). In this case you can use this in your test:

```php
$this->output(function() use ($class) {
    $this->boolean($class->funcOne())->isTrue();
});
```

The [`output`](http://docs.atoum.org/en/latest/asserters.html#output-anchor) asserter will capture the output. You won't see it in the report anymore and, if you need, you'll be able to asserton it.

**Comment by R11T** [comment]
Thanks a lot @Hywan @jubianchi, i'll try to adapt yours preco. for my specific case.

In my opinion, you can close this topic.

Regards. Once Again, thanks for atoum!

**Comment by jubianchi** [comment]
👍
