### ISSUE TITLE
Filter argument -d exits without output

### ISSUE THREAD

**Issue by DIOHz0r** [atoum/atoum#780]
Hello,

I'm having a extrange behavior using the filter –directories in a directory. 

If I have more than 11 files the atoum commands exits without reason and output. If I have 11 or less files the tests in that directory works perfect.

Is this ok or is a bug?.

**Comment by jubianchi** [comment]
Wow, seems really strange!

Could you give us more information please?

Which atoum version your are using?
Can you provide a minimal example where you reproduce the bug ?

**Comment by DIOHz0r** [comment]
Yes, its very strange the atoum version used is 3.2.0 and the comand of the error looks like this...

vendor/bin/atoum -ft -bf tests/bootstrap.php --max-children-number 1 -d tests/suite-integration/

I have to use this command to make the tests runs

for f in `ls tests/suite-integration/`; do vendor/bin/atoum -ft -bf tests/bootstrap.php --max-children-number 1 -f tests/suite-integration/$f; done;

You can see the error at this link https://travis-ci.org/DIOHz0r/flyve-mdm-glpi-plugin/jobs/303164900#L939 and I have confirm this in a local machine moving the files between their real directory to other directory or a new one.

**Comment by jubianchi** [comment]
Thanks for the details.

I can't get your test suite to run on my local machine, I always get "Error accessing config table" errors. It seems that the test database is emptied each time I start the test suite.

**Comment by DIOHz0r** [comment]
Check the steps on before_script routine in .Travis.yml file

**Comment by Hywan** [comment]
@DIOHz0r Do you have any error on your log files?

**Comment by DIOHz0r** [comment]
Hi @Hywan, I don't have any error in my log of the project and I can run the tests with the -f filter without problems, Is there any other log to look for?.

**Comment by DIOHz0r** [comment]
Hello, 

This issue was because an error from our platform which was throwing an 255 PHP error, so is not your fault.
