### ISSUE TITLE
HTML report sometimes add extra parent path

### ISSUE THREAD

**Issue by trasher** [atoum/atoum#783]
Sometimes (I cannot really tell when it happens), some generated coverage HTML files have a wrong path. This affetcs the top link and the path to the CSS file as well (well, at least).

On a correct generated file, I'll have `src="screen.css"` but `src="../../screen.css"` on wrong ones.

**Comment by Grummfy** [comment]
so you speak about the html report inside atoum, not the one in the report extension?

**Comment by trasher** [comment]
Yes, see our `.atoum.php` file: https://github.com/glpi-project/glpi/blob/9.2/bugfixes/.atoum.php
