### ISSUE TITLE
New annotations to target the SUT being covered

### ISSUE THREAD

**Issue by Hywan** [atoum/atoum#784]
Hey :-),

I would like to make a new proposal.

### Currently

atoum uses the name of the test suite (i.e. a class name of kind `foo\test\unit\bar\baz`) to deduce the name of the SUT (i.e. resp. `foo\bar\baz`).

The name of the SUT is used to filter the code coverage data to compute the score of that particular SUT.

### The problem

When running integration tests, or [tests written with PHPUnit](https://github.com/atoum/phpunit-extension), the name of the SUT is unknown. Thus, there is no code coverage scores.

### A solution

A simple and non-intrusive solution would be to add a new annotation:

  * `@tests N[,N]*` where `N` is a valid fully-qualified name.

This annotation will say that the annoted test suite or test case tests the particular entities.

#### Alternative annotation names

  * `@covers` ([inspired by PHPUnit](https://phpunit.de/manual/current/en/appendixes.annotations.html#appendixes.annotations.covers)),
  * `@maps`.

Thoughts?

**Comment by Grummfy** [comment]
Sorry but what's SUT?

**Comment by Hywan** [comment]
System Under Test. Most of the time: The class being tested.

**Comment by Grummfy** [comment]
Perhaps, we should think a bit deeper. Like if we can determine the sut => go, otherwise use the detection from the annotation (not big fan of it) or from a setter inside the initialization part?

**Comment by Hywan** [comment]
This annotation is also appropriate when the test suite covers a function or a set of functions for instance. They are still unit tests, but we can't determine the SUT by looking at the test suite.

**Comment by mageekguy** [comment]
> The name of the SUT is used to filter the code coverage data to compute the score of that particular SUT.

Not only, this information is also used to allow `$this->newTestedInstance`.
Moreover, atoum was made to test object oriented code, so using it to test function is out of its scope.
And finaly, annotation in atoum are wrapper which call class method, so the @Grummfy's proposition to add the setter seems perfectly legit, but, the [setter already exists](https://github.com/atoum/atoum/blob/master/classes/test.php#L1042) ;).
And warning… the method `test::getTestedClassName()` is used in the constructor of  `test` class via `test::setAssertionManager()`, so it is not so easy to add annotation management…

**Comment by Hywan** [comment]
> Not only, this information is also used to allow `$this->newTestedInstance`.

Indeed, but that's not the point :-).

> Moreover, atoum was made to test object oriented code, so using it to test function is out of its scope.

Many people including me use atoum for unit testing, integration testing, system testing, [documentation testing](https://github.com/hoaproject/Kitab/), [HTTP testing](https://github.com/Hywan/atoum-apiblueprint-extension) etc. atoum is a test framework, not only a _unit object-oriented_ test framework.

> And finaly, annotation in atoum are wrapper which call class method

Yes, kind of:

https://github.com/atoum/atoum/blob/24ec4c46f4036113439e1e38e92252d65a328bfa/classes/test.php#L1632-L1698

The proposal is to agree on a name to call `setTestedClassName` if we decide to restrict it to class-like entities only.

**Comment by mageekguy** [comment]
Even if you use it for other purposes, atoum was build as a unit object-oriented test framework, strictly.

**Comment by Grummfy** [comment]
Reading here and IRC, for me, we are clear that the base goal of atoum is unit testing and yes we can extends it. I think there is more than one proposal and usage in this way.

Using annotation to fill $this->setTestedClassName seems good. Just remember that atoum have some automation related to class detection and we must be carefull about it. Otherwise seems good

**Comment by jubianchi** [comment]
I agree with @mageekguy: atoum was designed with unit testing at class level in mind so adding such an annotation would fail this particular goal.

@Hywan what about adding this annotation in the phpunit extension? We are trying to "fix" a problem in the extension so I would say that the annotation (or any other mean of doing what you suggest) should be implemented there.

Thoughts?

**Comment by Hywan** [comment]
The goal of this proposal covers me than the PHPUnit extension. It also includes integration test, or unit test for functions for instance.

But yes, PHPUnit has the `@covers` annotation, so we can implement it in the extension to increase the parity.

**Comment by jubianchi** [comment]
> It also includes integration test, or unit test for functions for instance.

Keep in mind that atoum was not originally designed to solve those problems. We could add tools to ease writing such test in atoum but we will always face limitations.

Or we could make atoum a bit more open and covers such use cases using dedicated extensions.
