### ISSUE TITLE
constant asserter

### ISSUE THREAD

**Issue by Grummfy** [atoum/atoum#786]
Hello,
\mageekguy\atoum\asserters\constant::setWith
we don't chack that the given value is a constant. for me we should have something like this

instead of
```php
$this->constant(PHP_VERSION)->isEqualTo('6.6.6');
```
We should have
```php
$this->constant('PHP_VERSION')->isEqualTo('6.6.6');
```
in this case we can do
```php
    public function setWith($value)
    {
        if (defined($value) === true) {
            $this->pass();
        } else {
            $this->fail($this->_('%s is not a constant', $this));
        }

        parent::setWith(constant($value));

        return $this;
    }
```

**Comment by Hywan** [comment]
If the constant does not exist, PHP will raise an error, so what's the point here?
In some cases, PHP could consider undefined constants as strings, but it has been deprecated, or it's about to be (I can't find the RFC).

**Comment by Grummfy** [comment]
the asserter that exist today is not marking any test to validate that we have a constant. This is the point.

**Comment by mikaelrandy** [comment]
I agree with the point that atoum's asserters usually ensure input variable type is correct.
I'm not sure each asserter do this check, but it could be a good idea to avoid this kind of behavior : 
```php
$this->constant($foo)->isEqualTo('bar');
```

But, as the `constant` asserter seems to have a unique `isEqualTo` assertion, it's not a big deal.

On the other hand, I'm not convinced by transform constant name into string and add another layout to extract constant content.
To keep test code as coherent as possible, I think we should keep `$this->constant(PHP_VERSION)` syntax.

**Comment by Hywan** [comment]
> the asserter that exist today is not marking any test to validate that we have a constant. This is the point.

And it's safe because PHP does it. So what's the point?

**Comment by Grummfy** [comment]
ok, so let's close it.
