### ISSUE TITLE
Fatal error when creating mock on class using return type declaration

### ISSUE THREAD

**Issue by srogier** [atoum/atoum#787]
Hello,

I'm trying to create a mock on a class which uses return type declaration.

But, this fails with a fatal error like this one :

```
Error FATAL ERROR in /var/www/html/tests/units/Foo.php on unknown line, generated by file /var/www/html/vendor/atoum/atoum/classes/mock/generator.php(205) : eval()'d code on line 2:
Declaration of mock\Foo\Bar::returnWithTypeHinting() must be compatible with Foo\Bar::returnWithTypeHinting(): array
```

I have this issue on both 3.2.1 and dev-master.

The issue can be reproduced with this code.

```php
<?php

namespace Foo {

    class Bar
    {
        public function returnWithTypeHinting(): array
        {
            return [];
        }

        public function methodToTest()
        {
            return 42;
        }
    }
}


namespace tests\units\Foo {
    class Bar extends \atoum\test
    {

        public function testMethodToTestWithoutMock()
        {
            $object = new \Foo\Bar();

            // works fine
            $this
                ->integer($object->methodToTest())
                ->isEqualTo(42)
            ;
        }

        public function testMethodToTestWithMock()
        {
            // will trigger a fatal error
            // Error FATAL ERROR in /var/www/html/tests/units/Foo.php on unknown line, generated by file /var/www/html/vendor/atoum/atoum/classes/mock/generator.php(205) : eval()'d code on line 2:
            // Declaration of mock\Foo\Bar::returnWithTypeHinting() must be compatible with Foo\Bar::returnWithTypeHinting(): array
            $object = new \mock\Foo\Bar();

            $this
                ->integer($object->methodToTest())
                ->isEqualTo(42)
            ;

        }
    }
}

```

This is the output of my php -v

```
localUser@7a136e176977:/var/www/html$ php -v
PHP 7.1.9 (cli) (built: Sep 15 2017 00:11:09) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.6.0beta1, Copyright (c) 2002-2017, by Derick Rethans
    with blackfire v1.18.0~linux-x64-non_zts71, https://blackfire.io, by SensioLabs

```

Have you any idea about fixing this error ? 
Did I misuse the mock functionality ?

Thanks :)

**Comment by Grummfy** [comment]
that's realy odd, I try to run your code and got 0 issue

composer require atoum/atoum 
and 
composer require atoum/atoum:dev-master

vendor/bin/atoum -f test.php

success

**Comment by Grummfy** [comment]
Here is the docker I used to test 

{code}
FROM php:7.1.9-cli

RUN apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get upgrade -y --no-install-recommends && \
#	DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends blackfire-agent && \
	pecl update-channels && \
#	docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && \
#	docker-php-ext-install pdo_mysql gd intl pcntl bcmath mbstring exif && \
	pecl install -a xdebug && \
	docker-php-ext-enable xdebug && \
	version=$(php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;") \
    && curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/linux/amd64/$version \
    && tar zxpf /tmp/blackfire-probe.tar.gz -C /tmp \
    && mv /tmp/blackfire-*.so $(php -r "echo ini_get('extension_dir');")/blackfire.so \
    && printf "extension=blackfire.so\nblackfire.agent_socket=tcp://blackfire:8707\n" > $PHP_INI_DIR/conf.d/blackfire.ini && \
	DEBIAN_FRONTEND=noninteractive apt-get autoremove -y && \
	rm -rf \
		/var/lib/apt/lists/* \
		/tmp/* \
		/var/tmp/*

RUN echo 'xdebug.remote_enable=1' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
	echo 'xdebug.remote_autostart=0' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
	echo 'xdebug.remote_port=9000' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
	echo 'xdebug.max_nesting_level=1000' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
	echo 'xdebug.remote_connect_back=1' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
	echo 'xdebug.idekey=PHPSTORM' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
	echo 'xdebug.remote_host=' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
	echo 'log_errors = On' > /usr/local/etc/php/conf.d/error-log.ini && \
	echo 'html_errors = On' >> /usr/local/etc/php/conf.d/error-log.ini && \
	echo 'display_errors = On' >> /usr/local/etc/php/conf.d/error-log.ini && \
	echo 'display_startup_errors = On' >> /usr/local/etc/php/conf.d/error-log.ini && \
	echo 'error_reporting = E_ALL' >> /usr/local/etc/php/conf.d/error-log.ini
{code}

docker run -ti --rm -v ${PWD}:/toto -w /toto TheHashFromDocker bash
vendor/bin/atoum -f test.php

and still working

**Comment by srogier** [comment]
Thanks @Grummfy for your answer. It helps to find the real issue.

I thought isoling the unit test was enough, but it wasn't.

Actually we used an old version of atoum/visibility-extension, and given that the test doesn't modify visibility, I forgot to disable the extension during the test (and I didn't figure of this extension with this message error)

So, after upgrading atoum/visibility-extension it works fine.

Thanks again and sorry for the irrelevant issue.

**Comment by Grummfy** [comment]
thanks, don't hesitate to create another issue if required
