### ISSUE TITLE
Empty index coverage report

### ISSUE THREAD

**Issue by DIOHz0r** [atoum/atoum#788]
Hello,

We run atoum with the report extension using the following steps: 

```console
# vendor/bin/atoum -ft -bf tests/bootstrap.php -d tests/suite-install  --ncc
# vendor/bin/atoum -ft -bf tests/bootstrap.php -d tests/suite-unit 
# vendor/bin/atoum -ft -bf tests/bootstrap.php -d tests/suite-integration 
# vendor/bin/atoum -ft -bf tests/bootstrap.php -d tests/suite-uninstall --ncc
```

For some logic reason we need this steps to setup the platform environment. All the reports are dumped to 'build/coverage' directory, so when the tests finished the index page of the report is empty.

Which is the best way to use the steps and have a full report of all classes?

**Comment by jubianchi** [comment]
The report is re-generated on each run.

@DIOHz0r when you run the last command (the one with `-ncc`) no code-coverage is collected so the report is empty. We should look at the extension and make it do nothing if the `-ncc` flag is used.
