### ISSUE TITLE
loop and filter issue

### ISSUE THREAD

**Issue by orthagh** [atoum/atoum#793]
I'm currently trying to find a 'vicious' bug in my code :p
And i encounter an issue with atoum

When i try to filter on a specific test, it's ok, i have my test
`php vendor/bin/atoum --debug  -mcn 1 -bf tests/bootstrap.php -d tests/LDAP -no-cc -m "tests\\units\\AuthLDAP::testOtherAuth"`

If i add loop mode 
`php vendor/bin/atoum --debug  -mcn 1 -bf tests/bootstrap.php -d tests/LDAP -no-cc -m "tests\\units\\AuthLDAP::testOtherAuth" -l`

cli answer:
```
GLPI dataset version 4.2 already loaded

> atoum path: ...
> atoum version: 3.2.0
> PHP path: /usr/bin/php7.2
> PHP version:
=> PHP 7.2.2-3+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb  6 2018 16:11:23) ( NTS )
=> Copyright (c) 1997-2018 The PHP Group
=> Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
> Total test duration: 0.00 second.
> Total test memory usage: 0.00 Mb.
> Running duration: 0.00 second.
Success (0 test, 0/0 method, 0 void method, 0 skipped method, 0 assertion)!
Press <Enter> to reexecute, press any other key and <Enter> to stop...
```

**Comment by Grummfy** [comment]
Thanks for the report

To try to deblock you, perahps you could try to move the argument about loop before other args to see if it change something ?

**Comment by orthagh** [comment]
i tested at several position (before `debug`, before `mcn`, etc), same behavior.

**Comment by Grummfy** [comment]
I can reproduce the error
https://gist.github.com/Grummfy/29a77e05eee0c8e3eafa9523bef7040d

it seems that is the combinaison of loop + filter on method + limitating the  number of maximum sub process

**Comment by Grummfy** [comment]
the bug is fixed on the current version of master. So with the next release, it will fixed.
If you absolutely need it, just use the master or wait for the next release that should be out in the next few weeks. Thanks for the report

**Comment by Grummfy** [comment]
@orthagh update atoum, you should have the fix with the new version ;)
