### ISSUE TITLE
Test class * is not in a namespace which matches pattern '#(?:^|\\)tests?\\units?\\#i'

### ISSUE THREAD

**Issue by AlexPravdin** [atoum/atoum#817]
Hello.
I have the standard Symfony 4.2 application. By default tests are located in the `tests` directory and have the namespace `App\Tests`. When I try to run a test in that directory I always see the anoying warning:

```
Test class 'App\Tests\HelloWorld' is not in a namespace which matches pattern '#(?:^|\\)tests?\\units?\\#i'
```
Why so? How to disable it or configure the correct namespace?

**Comment by janbodnar** [comment]
I bumped into the same issue today. It is a documentation issue; the magic behind the atoum tests should be clearly IMHO stated on the front page. If not for this ancient tutorial https://github.com/atoum/netbeans-sample/blob/master/README.md, I would be able to make it work. 

What I have found:

1) The test namespace must include `tests/units`
2) The test namespace must match the tested class namespace; 
        e.g.` tests/units/App/Producer/MessageProducer`
3) The test class must match the tested class name; e.g. must not be `MessageProducerTest`. 
This has implications for autoloading. 
4) The tested method name must start with `test`. 

Failing to comply with these magic expectations will lead to errors such as 
`Tested class 'App\MessageProducer' does not exist for test class 'tests\units\App\MessageProducer' `

**Comment by Grummfy** [comment]
hi, this is explain several times in the documentation. But fell free to explain where we should add an extra explanation about it in the documentation to make it clearer. I can understand how perturbating it is.

**Comment by janbodnar** [comment]
Hello, everybody reads the documentation on the Github front page, so I would put those 4 points there titled e.g. **Atoum test convensions**.

**Comment by Grummfy** [comment]
Thanks, I have created an issue for it, feel free to create a PR or we will do it.
