### ISSUE TITLE
atoum has deleted all files

### ISSUE THREAD

**Issue by adojck** [atoum/atoum#823]
Hello,

At the moment I'm learning how to use atoum and I am doing some experiments. I wrote my class and test unit for it. Everything was working as expected.

Then I tried to get code coverage report working by installing xdebug on my system. After I installed and enabled xdebug, I ran atoum tests again and it failed with `copy` function unable to find file `screen.css`

At this point the least expected thing has happened. **I lost all my files in my working directory.**

Here is a short log of what I did:

```
[adomas@yoga 2019-05-20-workflow]$ php -r "var_dump(extension_loaded('xdebug'));"
Command line code:1:
bool(true)

[adomas@yoga 2019-05-20-workflow]$ ./vendor/bin/atoum -c coverage.php -f src/Adomas/ArrayTools/tests/units/Sum.php 
15<br>0> atoum path: /home/adomas/Workbench/Education/2019-05-20-workflow/vendor/atoum/atoum/bin/atoum
> atoum version: 3.3.0
> PHP path: /usr/bin/php
> PHP version:
=> PHP 7.3.5 (cli) (built: Apr 30 2019 21:05:09) ( NTS )
=> Copyright (c) 1997-2018 The PHP Group
=> Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies
=>     with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans
> Adomas\ArrayTools\tests\units\Sum...
[SS__________________________________________________________][2/2]
=> Test duration: 0.01 second.
=> Memory usage: 0.27 Mb.
Error: copy(/home/adomas/Workbench/Education/2019-05-20-workflow/vendor/atoum/atoum/resources/templates/coverage/screen.css): failed to open stream: No such file or directory in /home/adomas/Workbench/Education/2019-05-20-workflow/vendor/atoum/atoum/classes/adapter.php at line 14

[adomas@yoga 2019-05-20-workflow]$ ./vendor/bin/atoum -c coverage.php -f src/Adomas/ArrayTools/tests/units/Sum.php 
bash: ./vendor/bin/atoum: No such file or directory
```

Any ideas why it have happened? This time it was just learn/experiment code, so it's not that big of a deal, but next time it might be more painful to lose all data... Maybe this is some kind of atoum bug, or I misuse some feature?

**Comment by Grummfy** [comment]
hi,
it's the first time I see someone loose file with atoum.
The only explanation i see is something in the config file that make something strange.
It appears that in the time of report creation, an error appended. So for me it confirm that something is not correct in the coverage configuration.

Can you paste the config file here? And also the structure of the directory of your project?

**Comment by adojck** [comment]
My `coverage.php` was a copy of `vendor/atoum/atoum/resources/configurations/runner/coverage.php.dist` with edits to `Your project name`, `/path/to/destination/directory` (this one pointed to my working directory) and `http://url/of/treemap` which was url to the root...

I think I should have not defined everywhere path to my working directory in `coverage.php`, yes?

As I lost my all files, I can't paste exact config file here...

**Comment by Grummfy** [comment]
In the line
```
$coverageHtmlField = new atoum\report\fields\runner\coverage\html('Your project name', '/path/to/destination/directory');
$coverageTreemapField = new atoum\report\fields\runner\coverage\treemap('Your project name', '/path/to/destination/directory');
```
did you put the location of your working directory?
if yes, just adapt to a subdirectory. I think adding some explanation in this example file will be a great help. And also check that the report directory is not the current one. => I will create two issue about it ;)

**Comment by adojck** [comment]
Closing this issue. The reason why files are gone now clear. User fault :) Will be great if #824 will be done

**Comment by Grummfy** [comment]
thanks to confirm. It's perhaps user fault, but we should be more explicit (documentation, example, code security..)!
