### ISSUE TITLE
php8 test-it failing (8.0.1 -> ... incompatibility on two tests)

### ISSUE THREAD

**Issue by boskos-q** [atoum/atoum#855]
Hello,
PHP version: 
```
> atoum version: dev-master
> PHP path: /usr/local/bin/php
> PHP version:
=> PHP 8.0.3 (cli) (built: Mar 13 2021 02:32:59) ( NTS )
=> Copyright (c) The PHP Group
=> Zend Engine v4.0.3, Copyright (c) Zend Technologies
=>     with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies
```
For some reason atoum it's showing dev-master tho it's 4.0.0

Error from testing:
```
Failure (235 tests, 1861/1862 methods, 0 void method, 1 skipped method, 0 uncompleted method, 2 failures, 0 error, 0 exception)!
> There are 2 failures:

=> atoum\atoum\tests\units\mock\streams\fs\file::testFseek():
In file /var/www/vendor/atoum/atoum/tests/units/classes/mock/streams/fs/file.php on line 412, boolean() failed: boolean(false) is not true
-Expected
+Actual
@@ -1 +1 @@
-bool(true)
+bool(false)

=> atoum\atoum\tests\units\scripts\phar\generator::testRun():
In file /var/www/vendor/atoum/atoum/tests/units/classes/scripts/phar/generator.php on line 337, mock() failed: mock\phar::setStub(string(13) "605897c811b61", integer(-1)) is called 0 time instead of 1
[1] mock\phar::setStub(string(13) "605897c811b61", NULL)
> There is 1 skipped method:
=> atoum\atoum\tests\units\php::test__toStringWindows(): Linux OS is not supported
```

Note: I've run this in docker container from [nicolasbonnici](https://github.com/nicolasbonnici/docker-php8-sf5-nginx-pqsql-boilerplate) so you can also use it for testing or re-creating an issue by simply installing atoum in it via composer and running tests

**Comment by Grummfy** [comment]
hello,
I confirm that the first failed, exist since 8.0.1
and the second since php 8.0.2

It required to be fixed. But I didn't get the time to check if it fails and break atoum or if it's just the test that break (it's not always easy to test itself ;) )


thanks for the report

**Comment by boskos-q** [comment]
Thanks for the fast reply @Grummfy 
I just hope that you're this fast on fixing this as I'm in process of upgrading some packages to support php8 and atoum is used for testing in those packages :)

**Comment by Grummfy** [comment]
For the phar builder, the test issue is not an issue. For the testFseek, the best would be to create a use case that failed and validate that atoum report it properly.

Otherwise, for now I'm quiete busy and I don't really have time to dig deeper :(

**Comment by villfa** [comment]
`testFseek` probably fails because of the following change in PHP: https://github.com/php/php-src/commit/f1d11c118dfdc911f2f33babb9b2cba8bf5acb67
