### ISSUE TITLE
[mock] reset calls count

### ISSUE THREAD

**Issue by Oliboy50** [atoum/atoum#856]
Is it possible to reset the calls count of a mock?

For example, I'd like to make sure a request call is cached in a function, so if I call this function twice, I should see only 1 mock call:

```php
        $this
            ->if($my->func($client)
            ->then
                ->mock($client)
                    ->call('request')
                    ->exactly(1)
                    
                   // ... reset the $client mock calls count
                    
            ->if($my->func($client)
            ->then
                ->mock($client)
                    ->call('request')
                    ->exactly(0)
```

**Comment by Grummfy** [comment]
hello,
yes, of course is possible

https://docs.atoum.org/en/latest/how_to_write_test_cases.html#asserter

you can use

```
$mock->getMockController()->resetCalls() ;
// or
$this->resetMock($mock);
```

or
```
        $this
            ->if($my->func($client)
            ->then
                ->mock($client)
                    ->call('request')
                    ->exactly(1)
            ->assert('Something else to test')
            ->if($my->func($client)
            ->then
                ->mock($client)
                    ->call('request')
                    ->exactly(0)
```

Telll me if it solve your issue

**Comment by Oliboy50** [comment]
yes it is exactly what I was looking for, thank you

the problem is that I didn't search in this part of the doc 

only looked here https://docs.atoum.org/en/latest/asserters.html#mock and here https://docs.atoum.org/en/latest/mocking_systems.html
