### ISSUE TITLE
Atoum 4.1 to publish

### ISSUE THREAD

**Issue by Grummfy** [atoum/atoum#886]
### Discussed in https://github.com/atoum/atoum/discussions/885

* [x] check that every new modification is listed in changelog with their author
* [x] change the changelog to 4.1
* [x] tag the new commit to 4.1.0
* [ ] create new post about this release => later by Grummfy

**Comment by cedric-anne** [comment]
I updated the changelog in #887, based on https://github.com/atoum/atoum/compare/4.0.3...master

I cannot help on next steps.

**Comment by Grummfy** [comment]
done ;)

**Comment by Grummfy** [comment]
thanks for the help
