### ISSUE TITLE
Atoum 4.1 error extends class

### ISSUE THREAD

**Issue by kzacristo** [atoum/atoum#895]
I am trying to implement unit testing in my GLPI application but I am facing a difficulty with the error when the class to be tested is extending another class of my project.
![Captura de tela 2023-08-07 111111](https://github.com/atoum/atoum/assets/13594787/8f6756e0-7308-46c7-abfe-04e432679ca6)
I installed the atou via composer.
Folder structure
![Captura de tela 2023-08-07 111244](https://github.com/atoum/atoum/assets/13594787/4c9fc532-8cde-4305-a3f1-c07765d76394)
bootstrap.php file and test file
![Captura de tela 2023-08-07 111551](https://github.com/atoum/atoum/assets/13594787/3a2ca0f9-5762-4f5a-85aa-16b6b15343e3)
I would like to know how to resolve this error

**Comment by Grummfy** [comment]
close it's a discussion => https://github.com/atoum/atoum/discussions/896
